- .vscode/launch.json
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/README.md
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/meal_app/pubspec.lock
- packages/widgetbook/meal_app/stories/storybook.dart
- packages/widgetbook/pubspec.yaml
> Added documentation for Issue 4

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/cubit/categories/categories_cubit.dart
- packages/widgetbook/lib/src/models/organizers/category.dart
- packages/widgetbook/lib/src/models/organizers/expandable_organizer.dart
- packages/widgetbook/lib/src/models/organizers/folder.dart
- packages/widgetbook/lib/src/models/organizers/organizer.dart
- packages/widgetbook/lib/src/models/organizers/organizer_base.dart
- packages/widgetbook/lib/src/models/organizers/organizer_helper.dart
- packages/widgetbook/lib/src/models/organizers/organizer_helper/folder_helper.dart
- packages/widgetbook/lib/src/models/organizers/organizer_helper/organizer_helper.dart
- packages/widgetbook/lib/src/models/organizers/organizer_helper/story_helper.dart
- packages/widgetbook/lib/src/models/organizers/organizer_helper/widget_helper.dart
- packages/widgetbook/lib/src/models/organizers/organizers.dart
- packages/widgetbook/lib/src/models/organizers/story.dart
- packages/widgetbook/lib/src/models/organizers/widget_element.dart
- packages/widgetbook/lib/src/navigation/ui/tiles/spaced_tile.dart
- packages/widgetbook/lib/src/navigation/ui/tiles/tile.dart
- packages/widgetbook/lib/src/routing/router.dart
- packages/widgetbook/pubspec.yaml
- fixed collapsing of navigation tree elements on hot reload
- improved code structure and reduce redundant code
> Fixed navigation tree collapsing on hot reload

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/providers/injected_theme_state.dart
- packages/widgetbook/lib/src/widgets/device_render.dart
- packages/widgetbook/lib/src/widgets/no_theme.dart
- packages/widgetbook/lib/src/widgets/wrapper.dart
- packages/widgetbook/pubspec.yaml
- packages/widgetbook/test/src/providers/device_state_test.dart
- packages/widgetbook/test/src/providers/injected_theme_state_test.dart
- packages/widgetbook/test/src/widgets/device_render_test.dart
fixed issue #45
- fixed error thrown when switching to a theme that is not defined
- added a widget indicating that the current theme is not defined
> Implemented NoTheme widget

- packages/widgetbook/README.md
Added Linux as a supported platform in the documentation
#89 
> added Linux as a supported platform

- examples/widgetbook_annotation_example/lib/app.dart
- examples/widgetbook_annotation_example/lib/app.widgetbook.dart
- examples/widgetbook_annotation_example/pubspec.lock
- examples/widgetbook_annotation_example/pubspec.yaml
- examples/widgetbook_example/pubspec.lock
- examples/widgetbook_example/pubspec.yaml
- examples/widgetbook_example/stories/storybook.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/README.md
- packages/widgetbook_annotation/pubspec.lock
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.lock
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_models/CHANGELOG.md
- packages/widgetbook_models/pubspec.yaml
Changes to `Changelog` to document the most recent improvements.
> Release 1.0.3

- .github/workflows/deploy-example.yaml
- .github/workflows/example.yaml
added Google Cloud action to deploy example as demo.
#105
>  chore(widgetbook_example): adjusted action to deploy example app

- .github/workflows/deploy-example.yaml
- fix: corrected typo in deploy-example action
#117
> fix: corrected typo in deploy-example action

- CONTRIBUTING.md
- added contributing guidelines
> docs: added contributing guidelines

- examples/widgetbook_example/widgetbook/widgetbook.dart
- packages/widgetbook/lib/src/devices/widgetbook_device_frame.dart
- packages/widgetbook/lib/src/workbench/renderer.dart
- Added `MediaQuery` into the widget tree. 
closes #66 
closes #119
> fix: added MediaQuery for WidgetbookDeviceFrame

- README.md
Updated documentation because Widgetbook Cloud was not mentioned
> Add Widgetbook Cloud to READ ME

- examples/widgetbook_annotation_example/lib/app.dart
- packages/widgetbook_annotation/README.md
Added list type specifier for documentation and code. 
closes #134
> fix: example for locales does not compile

- melos.yaml
- packages/widgetbook/lib/src/models/organizers/expandable_organizer.dart
- packages/widgetbook/lib/src/models/organizers/widgetbook_category.dart
- packages/widgetbook/lib/src/navigation/organizer_provider.dart
Fixed broken navigator.
closes #156
> fix: expanding of elements within the navigation is not working

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- bumped version to `2.0.7-beta`
- added fixed issue to changelog
> chore(widgetbook): v2.0.7-beta

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/workbench/workbench_provider.dart
- packages/widgetbook/pubspec.yaml
- changed default for Orientation from `landscape` to `portrait`.
> fix: orientation defaults to landscape

- examples/widgetbook_annotation_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/README.md
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
Bumped version to release v2.0.9
> chore: v2.0.9

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/bool_knob.dart
- packages/widgetbook/lib/src/knobs/knobs.dart
- packages/widgetbook/lib/src/knobs/number_knob.dart
- packages/widgetbook/lib/src/knobs/options_knob.dart
- packages/widgetbook/lib/src/knobs/slider_knob.dart
- packages/widgetbook/lib/src/knobs/text_knob.dart
Fixed knob values not receiving updates when changing use-cases. 
While the submitted issue was related to text, other knobs were also not updating correctly.
closes #170 
> fix: knob values do not update when usecase changes

- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook-models.yaml
- .github/workflows/widgetbook.yaml
- melos.yaml
- packages/widgetbook/example/main.dart
- packages/widgetbook/lib/src/settings_panel/settings_panel.dart
- packages/widgetbook/lib/src/widgetbook_page.dart
- packages/widgetbook/test/src/knobs/bool_knob_test.dart
- packages/widgetbook/test/src/knobs/number_knob_test.dart
- packages/widgetbook/test/src/knobs/text_knob_test.dart
- fix: score of `widgetbook` and `widgetbook_generator`
- added script to check for score
closes #176 
> fix(widgetbook): score

- .github/workflows/deploy-example.yaml
- .github/workflows/example.yaml
- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook-models.yaml
- .github/workflows/widgetbook.yaml
- examples/knobs_example/pubspec.lock
- examples/widgetbook_annotation_example/pubspec.lock
- examples/widgetbook_example/pubspec.lock
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/styled_widgets/styled_scaffold.dart
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook/test/src/navigation/organizer_provider_test.dart
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.lock
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_device_frame/example/pubspec.lock
- packages/widgetbook_device_frame/pubspec.lock
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.lock
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_models/CHANGELOG.md
- packages/widgetbook_models/pubspec.yaml
- fixed widgetbook using an outdated widgetbook_model
> fix: widgetbook uses wrong models version

- examples/knobs_example/pubspec.lock
- examples/widgetbook_annotation_example/pubspec.lock
- examples/widgetbook_example/pubspec.lock
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook/test/mocks/filter_service_mock.dart
- packages/widgetbook/test/src/navigation/organizer_provider_test.dart
- packages/widgetbook_generator/pubspec.lock
> chore: mocktail v0.3.0

- docs.json
Add missing Projects link in Widgetbook Cloud section.
- #215
> Add missing Projects link in Widgetbook Cloud menu section

- docs.json
Remove _Annotations_ link from Widgetbook Generator menu section
- #213
> Remove annotations link from Widgetbook Generator menu

- docs/widgetbook-cloud/hosting.mdx
> remove links

- examples/widgetbook_annotation_example/lib/app.widgetbook.dart
- packages/widgetbook_generator/lib/generators/imports_generator.dart
Sorted import statements before code generation which will result in more deterministic and git-friendly code generation. 
closes #167
> fix: imports of file not deterministic

- docs/widgetbook/setup.mdx
added setup via `widgetbook_starter` brick.
> docs(widgetbook): :memo: add setup via widgetbook_starter brick

- packages/widgetbook_git/.github/workflows/ci.yml
- packages/widgetbook_git/.gitignore
- packages/widgetbook_git/CHANGELOG.md
- packages/widgetbook_git/LICENSE
- packages/widgetbook_git/README.md
- packages/widgetbook_git/analysis_options.yaml
- packages/widgetbook_git/example/example.dart
- packages/widgetbook_git/lib/src/bot.dart
- packages/widgetbook_git/lib/src/branch_reference.dart
- packages/widgetbook_git/lib/src/commit.dart
- packages/widgetbook_git/lib/src/commit_reference.dart
- packages/widgetbook_git/lib/src/diff_header.dart
- packages/widgetbook_git/lib/src/file_diff.dart
- packages/widgetbook_git/lib/src/git_dir.dart
- packages/widgetbook_git/lib/src/git_error.dart
- packages/widgetbook_git/lib/src/hunk.dart
- packages/widgetbook_git/lib/src/tag.dart
- packages/widgetbook_git/lib/src/top_level.dart
- packages/widgetbook_git/lib/src/tree_entry.dart
- packages/widgetbook_git/lib/src/util.dart
- packages/widgetbook_git/lib/widgetbook_git.dart
- packages/widgetbook_git/pubspec.yaml
- packages/widgetbook_git/test/git_dir_test.dart
- packages/widgetbook_git/test/git_test.dart
- packages/widgetbook_git/test/parse_test.dart
- packages/widgetbook_git/test/readme_test.dart
add forked version of `git` package while the PR is still work in progress
- closes #235
> feat(cli): :sparkles: add forked git package

- .vscode/settings.json
- packages/widgetbook_git/README.md
pushlish widgetbook_git to pub.dev
- closes #237
> chore(cli): :bookmark: publish widgetbook_git

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- add executables to `pubdev.yaml`
- upload to pub.dev
- closes #234
> feat(cli): :bookmark: publish CLI to pub.dev

- docs/widgetbook-cloud/review.mdx
Adjusted docs to use the new CLI
- closes #241
> docs: :memo: update Review docs

- bricks/widgetbook_app/CHANGELOG.md
- bricks/widgetbook_app/LICENSE
- bricks/widgetbook_app/README.md
- bricks/widgetbook_app/brick.yaml
add docs to `widgetbook_app` brick.
-closes #245
> feat: :sparkles: publish widgetbook_app brick

- packages/widgetbook_cli/pubspec.yaml
- bump cli version to `2.0.0-beta.8`
- closes #258
> chore: bump cli version

- docs.json
- docs/widgetbook-cloud/hosting.mdx
fix broken link to member management.
- closes #262
> fix: :bug: link does not work

- docs/widgetbook-cloud/review.mdx
add link to correct code
- related to, but not fixing #264
> fix: add link to correct code

- docs/widgetbook-cloud/hosting.mdx
remove outdated CLI text
- closes #266
> docs: :memo: remove outdated CLI text

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/pubspec.yaml
added warning indicating that generator files are missing to upload a review.
- closes #271
> fix: :bug: ambiguous warning for no generator themes

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/git-provider/git_provider.dart
- packages/widgetbook_cli/bin/git-provider/github/comment.dart
- packages/widgetbook_cli/bin/git-provider/github/comment.freezed.dart
- packages/widgetbook_cli/bin/git-provider/github/comment.g.dart
- packages/widgetbook_cli/bin/git-provider/github/github.dart
- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/pubspec.yaml
add PR comment with link to build
- closes #273
> feat: :sparkles: comment link to Build in PR

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/git-provider/git_provider.dart
- packages/widgetbook_cli/bin/git-provider/github/github.dart
- packages/widgetbook_cli/pubspec.yaml
- improve markdown on PR comments
- closes #275
> feat: :sparkles: improve markdown on PR comments

- bricks/widgetbook_starter/README.md
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/git-provider/git_provider.dart
- packages/widgetbook_cli/bin/git-provider/github/github.dart
- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/bin/models/deployment_data.dart
- packages/widgetbook_cli/bin/models/deployment_data.freezed.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.freezed.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.g.dart
- packages/widgetbook_cli/bin/review/devices/models/device_data.dart
- packages/widgetbook_cli/bin/review/locales/models/locale_data.dart
- packages/widgetbook_cli/bin/review/locales/models/model.dart
- packages/widgetbook_cli/bin/review/models/review.dart
- packages/widgetbook_cli/bin/review/models/review.freezed.dart
- packages/widgetbook_cli/bin/review/models/review.g.dart
- packages/widgetbook_cli/bin/review/text_scale_factors/models/text_scale_factor_data.dart
- packages/widgetbook_cli/bin/review/themes/models/theme_data.dart
- packages/widgetbook_cli/bin/widgetbook_http_client.dart
- packages/widgetbook_cli/pubspec.yaml
improved the CLI by adding a link to the Review
- closes #285
> feat: comment link to review

- examples/widgetbook_example/widgetbook/widgetbook.dart
- packages/widgetbook/example/main.dart
- packages/widgetbook/lib/src/addons/addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_data.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_data.freezed.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_selection.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_selection.freezed.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_selection_provider.dart
- packages/widgetbook/lib/src/workbench/renderer.dart
- Adding multi-property preview
- closes #289
> feat(widgetbook): :sparkles: addon multi property preview

- packages/widgetbook/lib/src/addons/addon.dart
- packages/widgetbook/lib/src/addons/addon_provider.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/workbench/preview.dart
- packages/widgetbook/lib/src/workbench/renderer.dart
- improved multi-property preview by supporting multiple addons
- closes #289
> refactor: :recycle: addon multi property preview

- packages/widgetbook/lib/src/addons/addon.dart
- packages/widgetbook/lib/src/addons/addon_panel.dart
- packages/widgetbook/lib/src/addons/device_addon/device_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/models/models.dart
- packages/widgetbook/lib/src/addons/models/panel_size.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/addons/widgets/addon_option.dart
- packages/widgetbook/lib/src/addons/widgets/addon_option_list.dart
- packages/widgetbook/lib/src/addons/widgets/addon_option_spacing.dart
- packages/widgetbook/lib/src/addons/widgets/widgets.dart
- adds visual indicator for selected items within a addon dialog
- closes #302
> fix: :bug: selected items not shown for addon

- examples/widgetbook_example/widgetbook/widgetbook.dart
- packages/widgetbook/lib/src/addons/addons.dart
- packages/widgetbook/lib/src/addons/cupertino_theme_addon/cupertino_theme_addon.dart
- packages/widgetbook/lib/src/addons/material_theme_addon/material_theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_provider.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_selection.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_selection.freezed.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_selection_provider.dart
- packages/widgetbook/lib/src/rendering/builders/app_builder.dart
- changes `ThemeAddon` to be `abstract` and generic
- adds `MaterialThemeAddon` exposing a `materialTheme` extension on `BuildContext`
- adds `CupertinoThemeAddon` exposing a `cupertinoTheme` extension on `BuildContext`
- closes #306
> feat: :sparkles: cupertino theme addon

- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
fixed rendering of `TextScale` selection.
- closes #303
> fix: :bug: addons show incorrect item

- bricks/widgetbook_starter/CHANGELOG.md
- bricks/widgetbook_starter/brick.yaml
bumps version and adds changelog information
- closes #319
> chore: :bookmark: release widgetbook_starter v0.1.0+2

- packages/widgetbook/lib/src/knobs/knobs.dart
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
Example added to knobs.dart
Resolves #321
> docs: improve documentation for options

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
- packages/widgetbook_cli/pubspec.yaml
- replaces hard-coded branch name with dynamic one from `git` package.
- closes #328 
> fix(cli): :bug: UseCaseParser contains hard-coded branch name

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/bin/widgetbook_http_client.dart
- packages/widgetbook_cli/pubspec.lock
- packages/widgetbook_cli/pubspec.yaml
changes endpoint
- closes #332
> fix: :bug: HttpClient connects to incorrect endpoint

- .github/workflows/widgetbook_exception.yaml
- mason.yaml
- packages/widgetbook_exception/.gitignore
- packages/widgetbook_exception/CHANGELOG.md
- packages/widgetbook_exception/LICENSE
- packages/widgetbook_exception/README.md
- packages/widgetbook_exception/analysis_options.yaml
- packages/widgetbook_exception/lib/src/widgetbook_exception.dart
- packages/widgetbook_exception/lib/widgetbook_exception.dart
- packages/widgetbook_exception/pubspec.yaml
- packages/widgetbook_exception/test/src/widgetbook_exception_test.dart
- Created a new package `widgetbook_exception`
- added test for
- updated changelog
- added workflows
- updated readme
> feat: :sparkles: implement-widgetbook-exception-package

- .gitmodules
adds https://github.com/widgetbook/widgetbook-demo as a `git` submodule
- closes #339
> feat: add `widgetbook-demo` as submodule

- .github/workflows/widgetbook-git.yaml
- packages/widgetbook_git/LICENSE
- packages/widgetbook_git/README.md
- packages/widgetbook_git/lib/src/git_dir.dart
- Updated the license, to include the company name
- Added method to get an actor
- Added method to get the current repository name
- Added github workflow
> feat: :memo: updated widgetbook git license and add 2 features

- docs.json
- docs/widgetbook-cli/overview.mdx
- docs/widgetbook-cloud/hosting.mdx
- docs/widgetbook-cloud/review.mdx
- improves docs to the most recent recommended approach
- adds docs on how to use Widgetbook CLI in version 3.0.x-beta.y
> docs: :memo: update to new CLI usage

- .vscode/launch.json
- examples/custom_theme_example/lib/main.widgetbook.dart
- examples/custom_theme_example/pubspec.lock
Do not merge
- fixes the custom theme problem
> fix: theme problem

- packages/widgetbook/test/src/addons/test_scale_factor/text_scale_factor_test.dart
- packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
- packages/widgetbook/test/src/addons/utils/addons.dart
- packages/widgetbook/test/src/addons/utils/extensions/widget_tester_extension.dart
- refactors text scale factor test suite
> refactor: :recycle: text scale addon test

- .github/workflows/deploy-widgetbook-feat.yml
- .github/workflows/deploy-widgetbook-main.yml
- adds two CI/CD pipelines for uploading Widgetbook to the Widgetbook Cloud
> ci: :green_heart: upload to Widgetbook Cloud

- packages/widgetbook_cli/bin/app/widgetbook_command_runner.dart
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/helpers/exceptions.dart
- packages/widgetbook_cli/bin/models/ci_args.dart
- packages/widgetbook_cli/bin/models/ci_args.freezed.dart
- packages/widgetbook_cli/bin/models/publish_args.dart
- packages/widgetbook_cli/bin/models/publish_args.freezed.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/helpers/test_data.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
- packages/widgetbook_cli/test/mocks/models/branch_reference.dart
- packages/widgetbook_cli/test/mocks/models/ci_args.dart
- packages/widgetbook_cli/test/mocks/models/models.dart
- fix CLI not longer exiting with error `code != 0` when no review is available
- closes #384
> fix(cli): :bug: fails pipeline when no generator files exist

- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/widgetbook_use_case.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/models/widgetbook_device_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_locales_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_text_scale_factor_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.g.dart
- packages/widgetbook_generator/lib/resolvers/use_case_resolver.dart
> feat(generator): :sparkles: add `designLink` property

- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/widgetbook_use_case.dart
- packages/widgetbook_cli/bin/review/use_cases/models/use_case_data.dart
- packages/widgetbook_cli/bin/review/use_cases/models/use_case_data.freezed.dart
- packages/widgetbook_cli/bin/review/use_cases/models/use_case_data.g.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/models/widgetbook_device_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_locales_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_text_scale_factor_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.freezed.dart
- packages/widgetbook_generator/lib/models/widgetbook_use_case_data.g.dart
- packages/widgetbook_generator/lib/resolvers/use_case_resolver.dart
- add `designLink` to `UseCaseData` class
> feat(cli): add design link to cli

- examples/widgetbook_example/lib/widgets/attributes/multiline_knob.dart
- examples/widgetbook_example/widgetbook/widgetbook.dart
- packages/widgetbook/lib/src/knobs/knobs.dart
- packages/widgetbook/lib/src/knobs/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/text_knob.dart
- packages/widgetbook/test/src/knobs/multiline_text_knob_test.dart
- packages/widgetbook/test/src/knobs/nullable_text_knob_test.dart
- packages/widgetbook/test/src/knobs/text_knob_test.dart
- Added multiline attribute to text knob 
- Added test for `text knob multiline.`
> feat(widgetbook): :zap: added text knob multiline

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/helpers/version.dart
- packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.dart
- packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.freezed.dart
- packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.g.dart
- packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_core/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_generator/test/src/code_generators/instances/widgetbook_widget_instance_test.dart
- packages/widgetbook_models/CHANGELOG.md
- packages/widgetbook_models/pubspec.yaml
- releases beta versions of `widgetbook`, `widgetbook_cli`, `widgetbook_annotation` and `widgetbook_generator`
> chore: widgetbook 3 beta release

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/bin/api/widgetbook_http_client.dart
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/git-provider/git_provider.dart
- packages/widgetbook_cli/bin/git-provider/github/github.dart
- packages/widgetbook_cli/bin/helpers/version.dart
- packages/widgetbook_cli/bin/models/create_review_response.dart
- packages/widgetbook_cli/bin/models/create_review_response.freezed.dart
- packages/widgetbook_cli/bin/models/create_review_response.g.dart
- packages/widgetbook_cli/bin/models/created_review.dart
- packages/widgetbook_cli/bin/models/created_review.freezed.dart
- packages/widgetbook_cli/bin/models/created_review.g.dart
- packages/widgetbook_cli/pubspec.yaml
- adds a link to a GitHub PR that points to the newly created Review
> feat(cli): :sparkles: link to review

- packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- fix properties not changing `onNavigate` via the browser's URL bar
> fix(widgetbook): :bug: properties not changing on navigate

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- release of widgetbook `v3.0.0-beta.4`
> chore(widgetbook): :bookmark: `v3.0.0-beta.4`

- packages/widgetbook_core/analysis_options.yaml
- packages/widgetbook_core/pubspec.yaml
- widgetbook_for_widgetbook/analysis_options.yaml
- widgetbook_for_widgetbook/pubspec.lock
- widgetbook_for_widgetbook/pubspec.yaml
Adds very_good_analysis to widgetbook_for_widgetbook & widget_book_core
> feat: ✨ adds very_good_analysis to widgetbook_for_widgetbook & widget_book_core

- packages/widgetbook_core/lib/src/icons/component_icon.dart
- packages/widgetbook_core/lib/src/navigation_tree/enums/enums.dart
- packages/widgetbook_core/lib/src/navigation_tree/enums/navigation_node_type.dart
- packages/widgetbook_core/lib/src/navigation_tree/models/models.dart
- packages/widgetbook_core/lib/src/navigation_tree/models/navigation_tree_node_data.dart
- packages/widgetbook_core/lib/src/navigation_tree/models/navigation_tree_node_data.freezed.dart
- packages/widgetbook_core/lib/src/navigation_tree/navigation_tree.dart
- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree.dart
- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree_item.dart
- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree_node.dart
- packages/widgetbook_core/lib/src/navigation_tree/widgets/widgets.dart
- packages/widgetbook_core/pubspec.yaml
- packages/widgetbook_core/test/helper/callback_mock.dart
- packages/widgetbook_core/test/helper/widget_tester_extension.dart
- packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_item_test.dart
- packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_node_test.dart
- packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_test.dart
- widgetbook_for_widgetbook/lib/app.widgetbook.dart
- widgetbook_for_widgetbook/lib/navigation/navigation_test_data.dart
- widgetbook_for_widgetbook/lib/navigation/navigation_tree.dart
- widgetbook_for_widgetbook/lib/navigation/navigation_tree_item.dart
- widgetbook_for_widgetbook/lib/navigation/navigation_tree_node.dart
- widgetbook_for_widgetbook/lib/search/search.dart
* Adds `NavigationTree`  
* `NavigationTree`  & `NavigationTreeNode` added to `widgetbook_for_widgetbook`
* Major changes on `NavigationTreeItem`
* 🧪 Added and updated tests
> feat: ✨ NavigationTree

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/addon_injector_widget.dart
- packages/widgetbook/lib/src/widgetbook_page.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/pubspec.yaml
- removes `routerData` from `Workbench` 
- fixes properties resetting when locale is changed
> fix(widgetbook): :bug: properties resetting when changing locale

- bricks/widgetbook_starter/CHANGELOG.md
- bricks/widgetbook_starter/README.md
- bricks/widgetbook_starter/brick.yaml
- docs.json
- docs/widgetbook-cli/overview.mdx
- docs/widgetbook-cloud/hosting.mdx
- docs/widgetbook-cloud/review.mdx
- docs/widgetbook/setup.mdx
- packages/widgetbook/lib/src/knobs/knobs.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.freezed.dart
- packages/widgetbook_cli/bin/review/api/create_review_response.g.dart
- packages/widgetbook_cli/bin/review/devices/models/device_data.dart
- packages/widgetbook_cli/bin/review/locales/models/locale_data.dart
- packages/widgetbook_cli/bin/review/locales/models/model.dart
- packages/widgetbook_cli/bin/review/models/review.dart
- packages/widgetbook_cli/bin/review/models/review.freezed.dart
- packages/widgetbook_cli/bin/review/models/review.g.dart
- packages/widgetbook_cli/bin/review/text_scale_factors/models/text_scale_factor_data.dart
- packages/widgetbook_cli/bin/review/themes/models/theme_data.dart
- merge `main` into `widgetbook-3`
> merge origin/main into widgetbook-3

- packages/widgetbook/README.md
- improves Readme content for `widgetbook` package
> refactor(widgetbook): :recycle: adjust content

- .github/dependabot.yaml
adds dependabot to Widgetbook
- closes #310
> ci: :green_heart: dependabot

- .github/dependabot.yaml
- melos.yaml
- adds command to generate test coverage report for all flutter packages
> chore: melos test coverage

- examples/custom_theme_example/lib/main.widgetbook.dart
- examples/knobs_example/lib/widgetbook.dart
- examples/widgetbook_annotation_example/lib/app.widgetbook.dart
- packages/widgetbook/lib/src/addons/cupertino_theme_addon/cupertino_theme_addon.dart
- packages/widgetbook/lib/src/addons/custom_theme_addon/custom_theme_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/material_theme_addon/material_theme_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/builder/functions/app_builder.dart
- packages/widgetbook/test/src/addons/custom_theme_addon_test.dart
- packages/widgetbook/test/src/addons/frame_addon/device_frame/device_frame_addon_test.dart
- packages/widgetbook/test/src/addons/frame_addon/frame_addon_test.dart
- packages/widgetbook/test/src/addons/locale_addon/locale_addon_test.dart
- packages/widgetbook/test/src/addons/utils/cupertino_app_theme.dart
- packages/widgetbook/test/src/addons/utils/material_app_theme.dart
- widgetbook_for_widgetbook/lib/app.dart
- fixes provider not found when`AddOn` is not defined (but accessed from the `materialAppBuilder`)
> fix(widgetbook): :bug: provider not found

- examples/custom_theme_example/lib/main.dart
- examples/custom_theme_example/lib/themes/app_theme.dart
- examples/custom_theme_example/lib/widgets/awesome_widget.dart
- examples/custom_theme_example/widgetbook/main.widgetbook.dart
- resolves warnings
- restructures folder structure
> refactor(examples): :recycle: custom_theme_example

- .vscode/settings.json
- examples/knobs_example/lib/main.dart
> refactor(examples): :recycle: knobs_example

- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-cli.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook-git.yaml
- .github/workflows/widgetbook-models.yaml
- .github/workflows/widgetbook.yaml
> ci: :bug: remove failing pana

- packages/widgetbook/test/src/addons/locale_addon/locale_addon_test.dart
- add test to verify that Widgetbook not longer ignores country codes
- fixes #232
> fix(widgetbook): :bug: ignores country codes

- .github/dependabot.yaml
Adds dependabot updates for each package
- closes #455
> fix: :bug: dependabot not working for pub

- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook_core/lib/src/navigation_tree/bloc/navigation_bloc.dart
- packages/widgetbook_core/test/src/navigation_tree/bloc/navigation_bloc_test.dart
Fixes hot reloading of `directories` and applies the existing `searchQuery` to the new `directories`
- fixes #387
- the other problem of #387 already has a test and works
> fix(core): :bug: hot reload of directories

- .github/dependabot.yaml
Changes the versioning strategy of dependabot.
> fix: :bug: dependabot not increasing version in yaml

- docs/widgetbook-cloud/hosting.mdx
- fixes link to GitHub action example
> docs: update link to GitHub action example

- docs/widgetbook-cloud/review.mdx
> docs: updated webhook guide

- docs/widgetbook-cloud/review.mdx
- updated link to GitHub webhook settings
> docs: updated link to GitHub webhook settings

- packages/widgetbook_cli/bin/git-provider/git_provider.dart
> fix(cli): :bug: directing to incorrect route

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
adds logic to ignore most recent commit and use user created commit instead 
- closes #497
> fix(cli): :bug: provides wrong `sha` when running on GitHub action pull-requests

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- widgetbook_cli@3.0.0-beta.20
> chore(release): publish packages

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- changed code to parse for more specific commit message
- closes #507
> fix(cli): :bug: skips most recent commit on base ref

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- new widgetbook_cli 3.0.0-beta.21 release
> chore(release): cli 3.0.0-beta.21

- packages/widgetbook_cli/bin/ci_parser/ci_parser.dart
- packages/widgetbook_cli/bin/ci_parser/ci_parser_runner.dart
- packages/widgetbook_cli/bin/ci_parser/ci_wrapper.dart
- packages/widgetbook_cli/bin/ci_parser/codemagic_parser.dart
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- adds support for Codemagic CI/CD
- closes #510
> feat(cli): support for Codemagic

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- widgetbook_for_widgetbook/pubspec.yaml
> chore(release): widgetbook 3.0.0-beta.11

- docs/widgetbook-cli/overview.mdx
- docs/widgetbook-cloud/hosting.mdx
- docs/widgetbook-cloud/review.mdx
- improves docs for review setup
> docs: :memo: improve review setup

- .github/workflows/deploy-widgetbook-feat.yml
- .github/workflows/deploy-widgetbook-main.yml
- bumps CLI version to `3.0.0-beta.22`
> ci(cli): :green_heart: bump CLI version to 3.0.0-beta.22

- melos.yaml
- widgetbook_for_widgetbook/pubspec.lock
> fix: :bug: melos configuration for widgetbook_for_widgetbook package

- packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
- fixes use cases not found in mono repos
> fix(cli): :bug: use cases not found

- README.md
- fixes broken link to Widgetbook website
> fix: broken link to Widgetbook website

- packages/widgetbook/pubspec.yaml
- packages/widgetbook_core/pubspec.yaml
Little typo. Typos are not harmful, but they are contagious. It keeps spreading all over the packages.
> chore: fix `homepage`s `utm_source`

- packages/widgetbook/lib/src/addons/device_addon/device_setting.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_setting.dart
- packages/widgetbook/test/src/addons/device_addon/frames/device_frame_builder_test.dart
- packages/widgetbook/test/src/addons/device_addon/frames/widgetbook_frame_builder_test.dart
- packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
- packages/widgetbook_addon/lib/src/addon_injector_widget.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon_scope.dart
- packages/widgetbook_addon/lib/widgetbook_addon.dart
- packages/widgetbook_addon/pubspec.yaml
One step closer to minimizing our dependencies.
> refactor(addon): drop `provider` dependency

- packages/widgetbook/test/src/routing/router_test.dart
Make CI ~~Great~~ **Green** Again!
> ci(widgetbook): skip router failing test

- packages/widgetbook_annotation/example/main.dart
- packages/widgetbook_generator/example/main.dart
These files are not analyzed by default, they escaped the renaming in #649.
> chore: update annotations in packages examples

- .github/workflows/_deploy.yml
- .github/workflows/deploy-widgetbook-feat.yml
- .github/workflows/deploy-widgetbook-main.yml
A reusable workflow for both deploy workflows.
> ci: create `_deploy` reusable workflow

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_core/CHANGELOG.md
- packages/widgetbook_generator/CHANGELOG.md
Update CHANGELOGs to match [the latest changes](https://github.com/widgetbook/widgetbook/compare/7869298d5c5c833f713bee4084a7d31862a96a33...a8d61722cf1af619de144a1f5d65f0839f3384e5).
> chore: update changelogs

- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/parsers/generator_parser.dart
- packages/widgetbook_core/lib/src/settings/widgets/dropdown_setting.dart
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/generators/json_builder.dart
Everything on Earth has a name, that's why these parameters deserve one as well.
> refactor: add param names for function types

- packages/widgetbook/pubspec.yaml
- packages/widgetbook_core/lib/src/navigation_tree/models/navigation_tree_node_data.dart
- packages/widgetbook_core/pubspec.yaml
- packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_test.dart
3 out of 4 `freezed` were removed.
Only the CLI package is left to melt!
> refactor(core): remove `freezed`

- .github/workflows/_package.yml
- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-cli.yaml
- .github/workflows/widgetbook-core.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook.yaml
Use the following guide to publish packages:
https://dart.dev/tools/pub/automated-publishing
> ci: use automated publishing

- .github/workflows/_package.yml
Fixes https://github.com/dart-lang/setup-dart/issues/68
> ci: set oidc token for publish

- analysis_options.yaml
- examples/screen_util_example/lib/widgetbook.dart
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook_cli/pubspec.yaml
Add all referenced packages as dependencies.
> chore: fix unreferenced packages

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/ci_parser/ci_parser_runner_test.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
> test: fix failing cli tests

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/app/workbench.dart
Discord thread explaining the issue more:
https://discord.com/channels/879618555560218625/1115298169878757456
> fix: add `key` to use cases

- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree_item.dart
- packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_item_test.dart
- widgetbook_for_widgetbook/lib/navigation/navigation_tree_item.dart
Remove the unused "More Icon".
> refactor(core): remove more icon from nav items

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/test/src/knobs/double_slider_knob_test.dart
> refactor: add label to `slider` knob

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/app_router.dart
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/test/src/app/router_test.dart
Widgetbook now Hot Reloads changes 🔥
> feat: support hot reloading

- docs/migration/3.0.0-beta-to-rc.mdx
- examples/custom_theme_example/pubspec.lock
- examples/custom_theme_example/pubspec.yaml
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/knobs_example/pubspec.lock
- examples/knobs_example/pubspec.yaml
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
New release candidate 🎉 with a lot of bug fixes and improvements.
> chore: v3.0.0-rc.2

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
https://github.com/widgetbook/widgetbook/assets/41103290/7f5fff93-a035-4b9a-96cc-1923f82dd8b0
> refactor: add `SafeArea` for frameless devices only

- examples/custom_theme_example/pubspec.lock
- examples/custom_theme_example/pubspec.yaml
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/knobs_example/pubspec.lock
- examples/knobs_example/pubspec.yaml
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
> chore: v3.0.0

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/generators/app_generator.dart
Import the file containing the use case function only.
> fix(generator): remove unused imports

- docs/addons/device-frame-addon.mdx
- docs/cookbook/custom-theme.mdx
Use `DeviceInfo` instead of `Device`.
> docs: fix custom devices

- docs.json
- docs/addons/alignment-addon.mdx
- docs/addons/overview.mdx
- examples/full_example/lib/widgetbook.dart
- examples/full_example/lib/widgetbook.generator.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/addons.dart
- packages/widgetbook/lib/src/addons/alignment_addon/addon.dart
- packages/widgetbook/lib/src/addons/alignment_addon/alignment_addon.dart
- packages/widgetbook/test/src/addons/alignment_addon/alignment_addon_test.dart
- sandbox/lib/widgetbook.dart
New Addon joining the party :tada:
The `AlignmentAddon` helps centering use-cases within the Workbench area.
```dart
Widgetbook(
addons: [
AlignmentAddon(),
],
// ...
)
```
> feat: add alignment addon

- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_generator/pubspec.yaml
> chore: fix documentation URL

- docs/getting-started/run.mdx
Fixes incorrect link in the run.mdx to point to the correct configuration page.
Fixes #812 
> docs: fix configuration page url

- docs.json
<kbd>⌥ </kbd> + <kbd>⇧ </kbd> + <kbd> F </kbd>
> docs: format `docs.json`

- docs.json
- docs/getting-started/install.mdx
- docs/widgetbook-cli/overview.mdx
- docs/widgetbook-cloud/review.mdx
Easily track versions used in docs using variables.
> docs: add `versions` variables

- packages/widgetbook/README.md
- packages/widgetbook_annotation/README.md
- packages/widgetbook_cli/README.md
- packages/widgetbook_generator/README.md
1. Unify headers style.
2. Remove outdated links.
3. Add "Documentation" Section.
> chore: update READMEs

- packages/widgetbook/lib/src/settings/dropdown_setting.dart
- packages/widgetbook/lib/src/settings/settings_panel.dart
- packages/widgetbook/lib/src/themes.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/test/helper/tester_extension.dart
- sandbox/lib/widgetbook.dart
Extract `TextField`,`DropdownMenu` & `ExpansionTile` themes.
> refactor: extract theme

- docs.json
- docs/faq/index.mdx
This is a page where we will capture questions that are coming quite often that we may not be able to add to the general pages on the documentation.
Generally, it's best to solve docs if questions require a longer answer or need better examples. Recipes will be on their way for those questions.
- [ x] I signed the [CLA].
- [ x] I updated/added relevant documentation (doc comments with `///`).
> docs: add FAQs page

- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/helpers/exceptions_test.dart
Fix tests that were a side-effect of #831
> test(cli): fix failing tests

- examples/full_example/lib/customs/custom_addon.dart
- examples/full_example/lib/widgetbook.theme.dart
- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook/lib/src/addons/alignment_addon/alignment_addon.dart
- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/lib/src/settings/settings_panel.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/test/src/navigation/tree_root.dart
- packages/widgetbook_cli/bin/git/git_dir.dart
- packages/widgetbook_cli/bin/git/top_level.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/git/git_dir_test.dart
- packages/widgetbook_cli/test/helpers/test_data.dart
- packages/widgetbook_generator/lib/generators/json_builder.dart
- sandbox/lib/navigation/root_data.dart
- Add missing trailing commas.
- Remove unused imports.
> chore: fix analysis infos

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/settings/knob_property.dart
- packages/widgetbook/test/src/knobs/boolean_knob_test.dart
- packages/widgetbook/test/src/knobs/string_knob_test.dart
The Checkbox for null knobs was initially not correct.
[Dircord thread](https://discord.com/channels/879618555560218625/879697921749184572/1135969352546529390)
> fix: correct initial checkbox value for null knobs

- .github/workflows/_package.yml
> ci: add webp to validate screenshots

- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_generator/pubspec.yaml
Use a sub-folder URL for each package, instead of sharing a single repo URL
> chore: update pubspec repos

- docs.json
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/knobs_example/pubspec.lock
- examples/knobs_example/pubspec.yaml
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
> chore: release v3.2.0

- docs.json
- docs/getting-started/mocking.mdx
Add a doc on how to mock and optimize widget dependencies particularly in Widgetbook context 
- [x ] I signed the [CLA].
- [ x] I updated/added relevant documentation (doc comments with `///`).
> docs: add mocking page

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/tree/tree_node.dart
- packages/widgetbook_generator/test/src/code/widgetbook_folder_instance_test.dart
> fix(generator): sort generated nodes

- packages/widgetbook/lib/src/widgetbook.dart
Use "Widgetbook" as a title for the root app.
> refactor: add `title` to the root `MaterialApp`

- docs.json
- docs/addons/time-dilation-addon.mdx
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/addons.dart
- packages/widgetbook/lib/src/addons/time_dilation_addon/addon.dart
- packages/widgetbook/lib/src/addons/time_dilation_addon/time_dilation_addon.dart
- packages/widgetbook/test/src/addons/time_dilation_addon_test.dart
- sandbox/lib/widgetbook.dart
Slow down animations using [`timeDilation`](https://api.flutter.dev/flutter/scheduler/timeDilation.html).
> feat: add time dilation addon

- docs.json
- docs/telemetry.mdx
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/build.yaml
- packages/widgetbook_generator/lib/builder.dart
- packages/widgetbook_generator/lib/src/generators/app_generator.dart
- packages/widgetbook_generator/lib/src/models/element_metadata.dart
- packages/widgetbook_generator/lib/src/telemetry/ci_keys.dart
- packages/widgetbook_generator/lib/src/telemetry/telemetry_reporter.dart
- packages/widgetbook_generator/lib/src/telemetry/usage_report.dart
- packages/widgetbook_generator/lib/widgetbook_generator.dart
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_generator/test/src/telemetry/usage_report_test.dart
- sandbox/build.yaml
To help us improve Widgetbook, starting from the next version, we will be collecting some anonymous usage reports that will help us define the future of this package, and improve its current state.
Read our [detailed documentation](https://docs.widgetbook.io/~893/telemetry) to know more about why we are doing it, how to opt-out and what we do collect.
> feat(generator): add telemetry

- docs.json
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/knobs_example/pubspec.lock
- examples/knobs_example/pubspec.yaml
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
> chore: release v3.3.0

- .github/workflows/common.yml
- examples/full_example/lib/widgetbook.generator.directories.g.dart
Sync out-of-date generated files.
And add a step `common / validate-uncommitted-changes` CI job to prevent that from happening again in the future.
> chore: sync generated files

- CONTRIBUTING.md
- docs.json
- docs/contribution/adding-example.mdx
- docs/contribution/code-reviews.mdx
- docs/contribution/get-started.mdx
- docs/contribution/pr-conventions.mdx
- docs/contribution/quick-guide.mdx
- docs/contribution/sync-your-fork.mdx
- docs/contribution/ways-to-contribute.mdx
- docs/contribution/workflow.mdx
This pr will add a comprehensive contribution guide to the docs. 
> docs: add contribution guide

- docs.json
To highlight Hacktoberfest, I temporarily added a link to the docs side menu. 
> docs: add Hacktoberfest to sidebar

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_use_case.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/code/widgetbook_use_case_instance.dart
Add design link to WidgetbookUseCase
#902 
> feat: add `designLink` to `WidgetbookUseCase`

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/context/context.dart
- packages/widgetbook_cli/bin/context/context_manager.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/context/context_manager_test.dart
- packages/widgetbook_cli/test/helpers/test_data.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
`Context` is now responsible for getting `Repository` through `workingDir`
> refactor(cli): move `repository` to `Context`

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
A new cleaner method called `validateRepository` is replacing `promptUncommittedChanges`.
> refactor(cli): replace `promptUncommittedChanges`

- packages/widgetbook_cli/lib/src/core/context_manager.dart
- packages/widgetbook_cli/lib/src/git/repository.dart
- packages/widgetbook_cli/test/src/core/context_manager_test.dart
Use `--show-toplevel` instead of `--git-dir` to get the repo's root directory.
> fix(cli): load repo from root

- packages/widgetbook_cli/bin/main.dart
- packages/widgetbook_cli/lib/src/core/context_manager.dart
- packages/widgetbook_cli/lib/src/utils/ci_manager.dart
- packages/widgetbook_cli/test/helper/mocks.dart
- packages/widgetbook_cli/test/src/core/context_manager_test.dart
Use the local context as a default one.
> refactor(cli): use default context

- docs/addons/custom-addon.mdx
- docs/contribution/code-reviews.mdx
- docs/contribution/quick-guide.mdx
- docs/cookbook/custom-theme.mdx
- docs/widgetbook-cli/overview.mdx
I Have fixed the links so that the user is navigated to the right pages.
Closes #954 
> docs: fix broken links

- docs/getting-started/setup.mdx
- docs/widgetbook-cloud/reviews.mdx
Adds instructions to complete the set up of knobs and addons and make them work in Widgetbook Cloud
> docs: Widgetbook Cloud knobs and addons set up instructions

- .github/workflows/_package.yml
- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-cli.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook.yaml
A job to detect if minimum versions are valid (which are currently not).
> ci: check minimum version compitability

- packages/widgetbook/lib/src/fields/double_input_field.dart
- packages/widgetbook/lib/src/fields/int_input_field.dart
- packages/widgetbook/lib/src/fields/num_input_field.dart
- packages/widgetbook/test/src/fields/num_input_field_test.dart
Prevent adding letters to numeric fields.
> refactor: add formatters to num fields

- .github/workflows/_package.yml
- .github/workflows/widgetbook-cli.yaml
Split `doctor` job into 3 new jobs:
1. `lint`
1. `test`
1. `pana`
> ci: split `doctor` job

- docs/widgetbook-cloud/quick-start.mdx
Updated outdated feature for member management as it was moved from projects to companies. This is correctly reflected in the projects.mdx page but not here.
> docs: update cloud members section

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/next.dart
- packages/widgetbook/lib/src/layout/responsive_layout.dart
- packages/widgetbook/lib/src/next/args/story_args.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/next/arg_builder.dart
- packages/widgetbook_generator/lib/src/next/args_class_builder.dart
- packages/widgetbook_generator/lib/src/next/extensions.dart
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- packages/widgetbook_generator/lib/src/next/story_generator.dart
- sandbox/lib/next/types_table.dart
If the parameter was not required or have a default value, the generated arg should be the same.
> refactor: support args of optional params

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/next/arg_builder.dart
- packages/widgetbook_generator/lib/src/next/args_class_builder.dart
- packages/widgetbook_generator/lib/src/next/component_builder.dart
- packages/widgetbook_generator/lib/src/next/extensions.dart
- packages/widgetbook_generator/lib/src/next/scenario_typedef_builder.dart
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- sandbox/lib/next/types_table.dart
1. Function Types:
- **Type**: `void Function(bool?)?`
- **With nullability**: `void Function(bool?)?`
- **Without nullability**: `void Function(bool)`
- **Expected**: `void Function(bool?)`
2. Generics:
- **Type**: `Future<bool?>?`
- **With nullability**: `Future<bool?>?`
- **Without nullability**: `Future<bool>`
- **Expected**: `Future<bool?>`
> fix(generator): preserve nullability of generic args

- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook.yaml
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/monorepo_example/apps/admin_app/pubspec.lock
- examples/monorepo_example/apps/admin_app/pubspec.yaml
- examples/monorepo_example/apps/main_app/pubspec.lock
- examples/monorepo_example/apps/main_app/pubspec.yaml
- examples/monorepo_example/packages/shared_ui/pubspec.lock
- examples/monorepo_example/packages/shared_ui/pubspec.yaml
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.yaml
- examples/screen_util_example/pubspec.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_test/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
Time to unlock new features for Widgetbook by enabling new language features from Dart 3.
> refactor: require dart 3

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/num_input_field.dart
[Discord Thread](https://discord.com/channels/879618555560218625/1185328153296638005/1187108790689087531)
> fix: use `T` codecs for `NumInputField`

- .github/workflows/upload-build.yml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/api/models/build_draft_request.dart
- packages/widgetbook_cli/lib/src/api/models/build_draft_response.dart
- packages/widgetbook_cli/lib/src/api/models/build_ready_request.dart
- packages/widgetbook_cli/lib/src/api/models/build_ready_response.dart
- packages/widgetbook_cli/lib/src/api/models/versions_metadata.dart
- packages/widgetbook_cli/lib/src/api/widgetbook_http_client.dart
- packages/widgetbook_cli/lib/src/commands/build_push.dart
- packages/widgetbook_cli/lib/src/commands/build_push_args.dart
- packages/widgetbook_cli/lib/src/commands/cloud.dart
- packages/widgetbook_cli/lib/src/commands/publish.dart
- packages/widgetbook_cli/lib/src/core/cli_command.dart
- packages/widgetbook_cli/lib/src/core/cli_commands_group.dart
- packages/widgetbook_cli/lib/src/core/cli_runner.dart
- packages/widgetbook_cli/lib/src/core/core.dart
- packages/widgetbook_cli/lib/src/core/environment.dart
- packages/widgetbook_cli/lib/src/models/use_case_metadata.dart
- packages/widgetbook_cli/lib/src/utils/zip_encoder.dart
- packages/widgetbook_cli/test/src/commands/build_push_test.dart
- packages/widgetbook_cli/test/src/commands/publish_test.dart
- packages/widgetbook_cli/test/src/core/cli_runner_test.dart
The new `cloud build push` command will be replacing the `publish` command.
> feat(cli): add new `build push` command

- docs/terminology.mdx
Update casing for Widgetbook in the terminology page.
> chore(docs): Update casing for Widgetbook

- docs/widgetbook-cloud/overview.mdx
> update overview docs

- docs/widgetbook-cloud/reviews.mdx
🔗 [Preview](https://docs.widgetbook.io/~1169/widgetbook-cloud/reviews#limitations)
> docs: add review limitations section

- docs/widgetbook-cloud/overview.mdx
- fixes typo in Cloud description
> docs: fix typo in cloud

- docs/widgetbook-cloud/reviews.mdx
- fixes typos on the review page
- removed updating state as this no longer exists
> docs: fix typos in cloud reviews

- docs/widgetbook-cloud/overview.mdx
> chore: update Widgetbook Cloud docs

- docs.json
Migrate to the new configuration that was introduced in invertase/docs.page#359
> docs: migrate to new structure

- docs/guides/annotations.mdx
updates the annotation page with an example
> chore: update use-case example

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/layout/desktop_layout.dart
- packages/widgetbook/lib/src/settings/settings_panel.dart
- packages/widgetbook/lib/src/themes.dart
To improve the UX of using knobs, no scrolling is now needed.
https://github.com/user-attachments/assets/3a81ff4b-e47c-4f2d-8d2c-02195ee50cee
> refactor: use tabs instead of accordion

- docs.json
- docs/cloud/security/overview.mdx
Adds a security overview page detailing our data handling practices regarding source code and personal identifiable information in the context of catalogued Widgets.
> docs: security overview

- docs/guides/monorepo.mdx
Adds extra commentary on how to add Widgetbook to a monorepo with Melos.
N/a
N/a
- [X ] I signed the [CLA].
> docs: add melos to monorepo guide

- docs.json
- docs/guides/quick-start.mdx
> docs: reference LeanCode VSC extension

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/state/widgetbook_state.dart
> feat: add `WidgetbookState.maybeOf`

- docs.json
- docs/cloud/setup/self-managed-gitlab.mdx
[🔗 Preview](https://docs.widgetbook.io/~1344/cloud/setup/self-managed-gitlab)
> docs: add self-managed gitlab setup

- docs/guides/use-cases.mdx
Fix misspelled use-case
Just found a typo, that's all!
> docs: fix typo

- docs/cloud/index.mdx
> docs: change cloud access link

- docs/cloud/security/overview.mdx
> docs: adjust security information

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/next/components_builder.dart
- packages/widgetbook_generator/lib/src/util/format.dart
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_generator/test/helpers/code.dart
This PR will unblock #1351, since `dart_style` is limiting our upgrades.
> refactor(generator): remove `dart_style`

- examples/full_example/macos/Flutter/Flutter-Debug.xcconfig
- examples/full_example/macos/Flutter/Flutter-Release.xcconfig
- examples/full_example/macos/Podfile
- examples/full_example/pubspec.lock
- examples/knobs_example/macos/Flutter/Flutter-Debug.xcconfig
- examples/knobs_example/macos/Flutter/Flutter-Release.xcconfig
- examples/knobs_example/macos/Podfile
- examples/knobs_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/screen_util_example/macos/Flutter/Flutter-Debug.xcconfig
- examples/screen_util_example/macos/Flutter/Flutter-Release.xcconfig
- examples/screen_util_example/macos/Podfile
- examples/screen_util_example/pubspec.lock
- packages/widgetbook/pubspec.yaml
- sandbox/macos/Flutter/Flutter-Debug.xcconfig
- sandbox/macos/Flutter/Flutter-Release.xcconfig
- sandbox/macos/Podfile
- sandbox/pubspec.lock
The dependency will be used by some upcoming features.
This change is done in a separate PR because it's causing a lot of noise in the diff.
> feat: add `url_launcher`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_node.dart
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_root.dart
- packages/widgetbook/lib/src/navigation/widgets/navigation_panel.dart
- packages/widgetbook/lib/src/navigation/widgets/stats_banner.dart
- packages/widgetbook/lib/src/navigation/widgets/widgets.dart
- sandbox/lib/navigation/stats_banner.dart
> feat: add stats banner

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
Support for v3 of package [inspector](https://pub.dev/packages/inspector).
> refactor: allow inspector v3

- docs/cloud/reviews/multi-snapshot.mdx
- docs/knobs/index.mdx
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/knob_config.dart
- packages/widgetbook_annotation/lib/src/knobs_configs.dart
- packages/widgetbook_annotation/lib/src/use_case.dart
- packages/widgetbook_annotation/lib/widgetbook_annotation.dart
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/cache/use_case_metadata.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
- packages/widgetbook_generator/lib/src/models/use_case_metadata.dart
- packages/widgetbook_generator/lib/src/util/dart_object.dart
- packages/widgetbook_generator/test/helpers/mock_use_case_metadata.dart
- sandbox/lib/navigation/expander_button.dart
Knobs are now supported in [Multi Snapshot Reviews](https://docs.widgetbook.io/cloud/reviews/multi-snapshot).
> feat: add multi snapshots for knobs

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/addons_configs_builder.dart
- packages/widgetbook_generator/pubspec.yaml
Related to dart-lang/source_gen#776
> refactor(generator): bump `source_gen` to 3.1.0

- docs.json
- docs/next/sam.mdx
Partial reverse of #1557
Restores SAM architecture guide.
> docs: restore sam guide
