- packages/widgetbook_models/lib/widgetbook_models.dart
Desktop screens is not exported in widgetbook_models
[#78 ](https://github.com/widgetbook/widgetbook/issues/78)
> Export desktop screens

- packages/widgetbook_annotation/README.md
- packages/widgetbook_generator/lib/services/tree_service.dart
- packages/widgetbook_generator/test/src/code_generators/instances/tree_service_test.dart
Skip `src` root directory when generating widgetbook
#80
> Skip src root folder

- packages/widgetbook/lib/src/models/organizers/expandable_organizer.dart
- packages/widgetbook/lib/src/models/organizers/widgetbook_folder.dart
- packages/widgetbook/lib/src/models/organizers/widgetbook_widget.dart
- packages/widgetbook/lib/src/navigation/ui/navigation_panel.dart
- packages/widgetbook/lib/src/providers/theme_provider.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/lib/src/widgets/controls_bar.dart
- packages/widgetbook/lib/src/widgets/tiles/story_tile.dart
- packages/widgetbook/lib/src/widgets/tiles/tile.dart
- packages/widgetbook/test/src/providers/theme_provider_test.dart
- packages/widgetbook_annotation/README.md
- packages/widgetbook_annotation/lib/src/widgetbook_app.dart
- packages/widgetbook_generator/lib/code_generators/instances/theme_mode_instance.dart
- packages/widgetbook_generator/lib/code_generators/instances/widgetbook_instance.dart
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/generators/widgetbook_generator.dart
- packages/widgetbook_generator/test/src/code_generators/instance_helper.dart
- packages/widgetbook_generator/test/src/code_generators/instances/device_instance_test.dart
- packages/widgetbook_generator/test/src/code_generators/instances/theme_mode_instance_test.dart
- packages/widgetbook_generator/test/src/code_generators/instances/tree_service_test.dart
- packages/widgetbook_generator/test/src/code_generators/instances/widgetbook_instance_test.dart
The widgetbook has always been started in dark mode. You can now set default startup theme mode in `@WidgetbookApp` annotation or in the `Widgetbook` class. 
#60 How to set a default theme?
> Add default theme parameter

- packages/widgetbook_annotation/lib/src/widgetbook_app.dart
- packages/widgetbook_generator/lib/code_generators/instances/base_instance.dart
- packages/widgetbook_generator/lib/code_generators/instances/boolean_instance.dart
- packages/widgetbook_generator/lib/code_generators/instances/widgetbook_category_instance.dart
- packages/widgetbook_generator/lib/code_generators/instances/widgetbook_folder_instance.dart
- packages/widgetbook_generator/lib/code_generators/instances/widgetbook_widget_instance.dart
- packages/widgetbook_generator/lib/code_generators/properties/property.dart
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/generators/widgetbook_generator.dart
- packages/widgetbook_generator/lib/services/tree_service.dart
- packages/widgetbook_generator/test/src/code_generators/instances/bool_instance_test.dart
- packages/widgetbook_generator/test/src/code_generators/instances/widgetbook_folder_instance_test.dart
You can now determine widget tree expand state, so you don't have to expand every time on restart
#86
> Add folders/widgets default expand state option

- examples/widgetbook_example/pubspec.yaml
- packages/widgetbook/lib/src/widgets/tiles/spaced_tile.dart
- packages/widgetbook/lib/src/widgets/tiles/tile.dart
- packages/widgetbook/test/src/widgets/tiles/tile_test.dart
Shows ellipses when a tile's name is too long, adds a tool tip to tiles that shows the full name. 
#63 
> Add constraint and overflow to tile #63

- examples/widgetbook_example/lib/themes/dark_theme.dart
- examples/widgetbook_example/widgetbook/widgetbook.dart
Fixed dark theme by 'inheriting' from `ThemeData.dark()`.
#106
> Fixed dark theme of example app

- .github/workflows/widgetbook-models.yaml
- .github/workflows/widgetbook.yaml
- examples/widgetbook_annotation_example/pubspec.lock
- examples/widgetbook_annotation_example/windows/flutter/generated_plugin_registrant.cc
- examples/widgetbook_annotation_example/windows/flutter/generated_plugins.cmake
- examples/widgetbook_example/pubspec.lock
- examples/widgetbook_example/widgetbook/widgetbook.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/README.md
- packages/widgetbook/lib/src/rendering/builders/device_builder.dart
- packages/widgetbook/lib/src/rendering/widgetbook_frame.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/pubspec.lock
- packages/widgetbook_generator/pubspec.lock
- packages/widgetbook_models/lib/src/devices/apple_devices.dart
- packages/widgetbook_models/lib/src/devices/device.dart
- packages/widgetbook_models/lib/src/devices/device.freezed.dart
- packages/widgetbook_models/lib/src/devices/device_size.dart
- packages/widgetbook_models/lib/src/devices/device_size.freezed.dart
- packages/widgetbook_models/lib/src/devices/resolution.dart
- packages/widgetbook_models/lib/src/devices/resolution.freezed.dart
- packages/widgetbook_models/pubspec.lock
- packages/widgetbook_models/pubspec.yaml
- Integrated [device_frame](https://pub.dev/packages/device_frame) into widgetbook. 
- added iPhone 13 models
- changed device classes to feature freezed
#112
> feature: added device_frame to widgetbook

- packages/widgetbook/README.md
Added section in the pub.dev docs on how to use widgetbook with a package that does not define a Flutter app.
#59
> docs: added how to use widgetbook with a package

- packages/widgetbook_annotation/lib/src/widgetbook_app.dart
removed `themeType` from the `WidgetbookApp.material` and `WidgetbookApp.cupertino` annotation constructors.
closes #129
> fix: app annotation exposes theme type property

- packages/widgetbook_generator/lib/resolvers/theme_resolver.dart
Added error message when `@WidgetbookTheme` is used on properties or non-static functions.
closes #130
> fix: missing error reporting when widgetbook theme is used on properties

- packages/widgetbook_annotation/README.md
- packages/widgetbook_annotation/example/main.dart
Replaced `@WidgetbookTheme.dark()` with `@WidgetbookTheme(name: ...)` for the example file and the documentation. 
closes #133
> fix: widgetbook theme dark does not exist

- packages/widgetbook/lib/src/rendering/builders/scaffold_builder.dart
- packages/widgetbook/lib/src/workbench/renderer.dart
Inserted ScaffoldMessenger into the tree based on the default `ScaffoldBuilder`
closes #148
> fix: scaffold messenger opens in widgetbook

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/organizer_provider.dart
- packages/widgetbook/lib/src/widgets/expanders/expand_button.dart
- packages/widgetbook/pubspec.yaml
fixed emitting of correct states when collapse all and expand all is clicked.
> fix: navigation tree collapsing and expanding does not work

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/workbench/renderer.dart
- packages/widgetbook/pubspec.yaml
- fixes reference to old `context`.
closes #180 
> fix(widgetbook): useCaseBuilder is called with old context

- packages/widgetbook/lib/src/rendering/builders/app_builder.dart
Added `Navigator` into the tree of the previewed app which will cause the Dialog to show up within the simulated app. However, for this to work properly showDialog has to be called with its `useRootNavigator` parameter to be set to `false`: 
```
showDialog(
context: context,
useRootNavigator: false,
builder: (_) => const AlertDialog(
title: Text('Dialog Title'),
content: Text('This is my content'),
),
);
```
closes #172
closes #190
> fix: dialog shows up in Widgetbook instead of the simulated device

- docs/widgetbook-cloud/hosting.mdx
corrected the file size of aot compiled version
> docs: changed file from .dart to .aot

- docs/widgetbook/knobs.mdx
This PR changes link to example file for knobs because the link is broken.
- #207
> docs(knobs): link to example file properly

- packages/widgetbook/lib/src/rendering/builders/app_builder.dart
Set `debugShowCheckedModeBanner` to `false`. 
closes #202 
closes #212
> fix: preview app shows debug banner

- docs/widgetbook-cloud/review.mdx
Removed faulty markdown from review documentation. 
This is related to https://github.com/invertase/docs.page/issues/215
> docs(widgetbook-cloud): :bug: removed faulty markdown from review documentation

- docs/widgetbook/knobs.mdx
fix a typo in the Knobs part of the docs.
> docs: fixed typo

- docs/widgetbook/knobs.mdx
changed the `description from `string` to the actual one from the implementation, which is `string?`.
> docs: changed `description` type to `string?`

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/README.md
- packages/widgetbook_cli/pubspec.yaml
rename executable of `widgetbook_cli` from `widgetbook-cli` to `widgetbook`.
- closes #254
> fix: :bug: rename cli to widgetbook

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/README.md
- packages/widgetbook_cli/pubspec.yaml
- change relative links from docs.page to global links. Links will now forward to [docs.widgetbook.io](https://docs.widgetbook.io).
- closes #268
> docs: :bug: change relative links to global links

- packages/widgetbook/lib/src/rendering/builders/app_builder.dart
Set `debugShowCheckedModeBanner: false` for other app builder than only `MaterialApp`.
Related to  #202, #212
> fix: preview app shows debug banner in other theme than material

- docs/widgetbook/setup.mdx
This PR fixes the command to generate the initial code using widgetbook_starter brick.
No issue
> Fixes mason brick widgetbook_starter usage in the docs

- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
Updated packages/widgetbook/pubspec.yaml to allow versions of go_router higher than 4.0 as the limitation of go_router 3.x.x was a blocker for many.
Changed From:   go_router: ^3.0.5
To:   go_router: ">=^3.0.5"
Resolves #253
> Updated widgetbook/pubspec.yaml to allow go_router > 4.0

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/std/stdin_wrapper.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
- adds check if terminal (`stdin`) exists in the runtime environment which will cause the expected user input to fail
- this might happen on CI/CD pipelines or when debugging the code since no input from the user can be obtained
- closes #348 
> fix(cli): :bug: CLI fails on environments without terminal

- examples/custom_theme_example/pubspec.yaml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_git/CHANGELOG.md
- packages/widgetbook_git/lib/src/git_dir.dart
- packages/widgetbook_git/pubspec.yaml
- adds trimming of `stdout` `String`
- removes versioning from `custom_theme_example` to simplify publishing of new versions
❗️Both `widgetbook_git` and `widgetbook_cli` are already published to their new versions.
- closes #358
> fix: reads actor and repository including newline

- packages/widgetbook/lib/src/addons/addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/addons/device_addon/device_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/frame.dart
- packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/frames/device_frame/device_frame.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/navigation/router.dart
- packages/widgetbook/lib/src/navigation/widgets/navigation_panel_wrapper.dart
- packages/widgetbook/lib/src/widgetbook_page.dart
- packages/widgetbook/pubspec.lock
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_panel.dart
- packages/widgetbook_core/lib/src/settings/widgets/sub_setting.dart
- widgetbook_for_widgetbook/lib/app.widgetbook.dart
- fixes navigation resetting
- fixes `Frame` setting to not show any value when app is started
- refactors spacing of panels from about 16 units to the default card's padding (which is 2). This provides more space for the preview of Widgets
- new: #441
- to be done: #444
> fix(widgetbook): :bug: navigation resets when use case changes

- packages/widgetbook/test/src/addons/frame_addon/frames/device_frame/device_frame_test.dart
- packages/widgetbook/test/src/addons/frame_addon/frames/no_frame/no_frame_test.dart
- packages/widgetbook/test/src/addons/frame_addon/frames/widgetbook_frame/widgetbook_frame_test.dart
- add test to check if `MediaQuery` is correctly applied for `DefaultDeviceFrame` and `WidgetbookFrame`
- closes #119 
- closes #383
> test(widgetbook): :white_check_mark: `DeviceFrameAddon` overrides `MediaQuery`

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
fix identifying merge commits with incorrect keywords
- closes #500
> fix(cli): :bug: identifying merge commits with incorrect keywords

- docs/widgetbook-cloud/review.mdx
Updates the docs with Repository name instructions for setting up the GitHub webhook for the Review feature
> docs: update GitHub webhooks instructions in review page

- packages/widgetbook/lib/src/addons/addon_injector_widget.dart
- allows users to not define `addons`
- closes #522
> fix(widgetbook): :bug: addons property cannot be empty

- examples/addon_example/lib/app.dart
- packages/widgetbook_annotation/lib/src/widgetbook_app.dart
- packages/widgetbook_annotation/test/src/widgetbook_app_test.dart
- widgetbook_for_widgetbook/lib/app.dart
- removes `name` property from `@WidgetbookApp` annotation
- closes #519
> fix(annotation): :bug: remove obsolete `name` property

- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/test/src/widgetbook_test.dart
- allows `directories` to be empty
- closes #529
> fix(widgetbook): :bug: requires `directories` to be not empty

- .github/workflows/deploy-widgetbook-feat.yml
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
The `gitProviderSha` method was using `git rev-list` to get the SHA of the triggering commit. This PR aims to use the following environment variables when running on CI.
| Provider | Environment Variable |
| :--- | :--- |
| GitHub | [`GITHUB_SHA`](https://docs.github.com/en/actions/learn-github-actions/variables#:~:text=github.com.-,GITHUB_SHA,-The%20commit%20SHA) |
| Codemagic | [`CM_COMMIT`](https://docs.codemagic.io/yaml-basic-configuration/environment-variables/#:~:text=from%20custom%20source-,CM_COMMIT,-Commit%20hash%20that) |
> fix(cli): use CI's commit environment variables

- packages/widgetbook_annotation/pubspec.lock
- packages/widgetbook_cli/pubspec.lock
- packages/widgetbook_generator/pubspec.lock
- widgetbook_for_widgetbook/pubspec.lock
Whenever `melos bs` is run, these files get edited and show up in version control, making doing most version control commands a bit painful.
> chore: sync outdated lock files

- analysis_options.yaml
Excluding `.widgetbook.dart` files from analysis leads to disabling the intellisense in VSCode. And since these files are manually written and not generated, so we need to make sure that they are following our lint rules as well.
Currently the only generated file is `examples/screen_util_example/lib/main.widgetbook.dart` and it can be safely excluded from analysis.
> chore: analyze `.widgetbook.dart` files

- packages/widgetbook_generator/pubspec.yaml
- bumps `json_annotation` dependency from 4.4.0 to 4.8.0
- bumps `analyzer` dependency from 4.0.0 to 5.10.0
> chore(deps): analyzer from 4.0.0 to 5.10.0 in /packages/widgetbook_generator

- .github/workflows/common.yml
- widgetbook_for_widgetbook/pubspec.lock
Usually when we update dependencies or packages' versions, we forget to run `melos bs` that updates all lock files with these changes. Causing the repo to have uncommitted changes after merging the proposed changes.
This CI job run a `git diff-index` command to make sure everything is up-to-date.
> ci: add `validate-uncommitted-changes` job

- packages/widgetbook/lib/src/addons/frame_addon/addons/device/device_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/addons/device/device_setting.dart
- packages/widgetbook/lib/src/addons/frame_addon/addons/no_frame/no_frame_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
- packages/widgetbook/lib/src/addons/frame_addon/frame_setting.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_setting.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_setting.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_setting.dart
- packages/widgetbook/lib/src/routing/router.dart
- packages/widgetbook/lib/src/widgetbook_page.dart
- packages/widgetbook_addon/example/main.dart
- packages/widgetbook_addon/lib/src/addon_injector_widget.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon_model.dart
- packages/widgetbook_addon/test/helper/custom_addon.dart
- packages/widgetbook_addon/test/src/addon_injector_widget_test.dart
Remove 2 abstract methods (`updateQueryParameters` & `settingFromQueryParameters`) from `WidgetbookAddOn` by providing the following alternatives respectively:
1.  `WidgetbookAddOn.addListener`: Allows `AddonInjectorWidget` to add a listener on all addons that has the same logic of `updateQueryParameters` (i.e. syncing the `setting` with the query parameters).
2. `WidgetbookAddOnModel.fromQueryParameter`: Move the responsibility of deserializing query parameters to the model instead of the addon itself (similar to `toJson` and `fromJson`).
| Before  | After |
| :--- | :---- |
| ![before](https://user-images.githubusercontent.com/41103290/232298916-aeac7ee1-ff02-40ad-9524-d93b5a761000.png) | ![after](https://user-images.githubusercontent.com/41103290/232298402-3ecbbd3e-1afa-42ac-8288-af6007 …
> refactor(addon): simplify api

- .github/workflows/_package.yml
- .github/workflows/base.yml
- .github/workflows/widgetbook-addon.yaml
- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-cli.yaml
- .github/workflows/widgetbook-core.yaml
- .github/workflows/widgetbook-exception.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook-git.yaml
- .github/workflows/widgetbook-models.yaml
- .github/workflows/widgetbook.yaml
The new reusable workflow is an alternative for [`very_good_workflows`](https://github.com/VeryGoodOpenSource/very_good_workflows) which wasn't working properly with `melos` and local dependencies.
> ⚠️ **Caveat**
> This PR does NOT support **test coverage** yet, and it will be done later on when we stablize the coverage across packages.
> ci: create `_package` reusable workflow

- packages/widgetbook/lib/src/addons/device_addon/device_addon.dart
- packages/widgetbook/lib/src/addons/device_addon/device_setting.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_setting.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_setting.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_setting.dart
- packages/widgetbook/lib/src/navigation/widgets/navigation_panel_wrapper.dart
- packages/widgetbook/lib/src/routing/router.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/test/src/addons/device_addon/frames/device_frame_builder_test.dart
- packages/widgetbook/test/src/addons/device_addon/frames/widgetbook_frame_builder_test.dart
- packages/widgetbook_addon/example/main.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon.dart
- packages/widgetbook_addon/lib/src/widgetbook_addon_model.dart
- packages/widgetbook_addon/test/helper/custom_addon.dart
Group each addon setting under a query parameter of its own name.
`/?device=iPhone13&orientation=landscape&frame=false`
`/?device={name:iPhone13,orientation:landscape,frame:false}`
> refactor(addon): group query params under name

- packages/widgetbook/lib/src/addons/device_addon/device_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/fields/dropdown_field.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/messaging/messaging.dart
- packages/widgetbook/lib/src/messaging/no_messaging.dart
- packages/widgetbook/lib/src/messaging/web_messaging.dart
- packages/widgetbook/lib/src/widgetbook.dart
- widgetbook_for_widgetbook/web/index.html
To support fields on Widgetbook Cloud, all fields are converted to JSON, and then sent [through web messages](https://api.dart.dev/stable/2.19.6/dart-html/Window/postMessage.html).
> feat: send fields json via web messaging

- .github/workflows/_package.yml
- melos.yaml
Setting [`MELOS_PACKAGES`](https://melos.invertase.dev/environment-variables#melos_packages) overrides all melos filters, thus the `--depends-on="build_runner"` filter was not working.
> ci: fix melos filters

- .github/workflows/_package.yml
- .github/workflows/common.yml
- .github/workflows/deploy-widgetbook-feat.yml
- .github/workflows/deploy-widgetbook-main.yml
Currently Widgetbbok doesn't work with Flutter 3.10, so pinning the workflows to the previous version until we fix it.
> ci: pin flutter version to 3.7.x

- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook/lib/src/addons/addons.dart
- widgetbook_for_widgetbook/lib/widgetbook.dart
These functions wouldn't scale well with custom addons and any changes to the addons API. So, better have them removed by now.
> refactor: remove configure addons functions

- examples/custom_theme_example/widgetbook/main.widgetbook.dart
- examples/knobs_example/lib/widgetbook.dart
- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook/lib/src/addons/addons.dart
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_addon/addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_setting.dart
- packages/widgetbook/test/src/addons/device_frame_addon/device_frame_addon_test.dart
- packages/widgetbook/test/src/widgetbook_test.dart
- widgetbook_for_widgetbook/lib/widgetbook.dart
This change has two reasons:
1. Imply that we are using `device_frame` under the hood. As third party addons will have the following naming convention in the future: `widgetbook_{package_name}_addon`.
2. Reserve the name `device_addon` for future usage, when we decide to dump `device_frame` and use our new custom implementation. This will make deprecation and migration easier.
> refactor: rename device addon

- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
When switching from any device back to "None" device, it wasn't working.
This teeny tiny fix makes it work again.
> fix: sync none device frame

- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/app/workbench.dart
- packages/widgetbook/lib/src/fields/boolean_field.dart
- packages/widgetbook/lib/src/fields/color_field.dart
- packages/widgetbook/lib/src/fields/double_input_field.dart
- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/lib/src/fields/string_field.dart
- packages/widgetbook/test/src/addons/common/custom_addon.dart
- packages/widgetbook/test/src/addons/device_frame_addon/device_frame_addon_test.dart
- packages/widgetbook/test/src/addons/locale_addon/locale_addon_test.dart
- packages/widgetbook/test/src/addons/test_scale_factor/text_scale_factor_test.dart
- packages/widgetbook/test/src/addons/theme_addon/cupertino_theme_addon_test.dart
- packages/widgetbook/test/src/addons/theme_addon/material_theme_addon_test.dart
- packages/widgetbook/test/src/addons/theme_addon/theme_addon_test.dart
- packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
Instead of having a local `setting` variable and updating it with each field change, a method called `settingFromQueryGroup` is added to parse query parameters into an addon's setting.
This change was made to avoid [calling `onChange` inside `Field`'s `build` method](https://github.com/widgetbook/widgetbook/blob/07fd5c19db24db3de00ca947ef2848cd4831cd4b/packages/widgetbook/lib/src/fields/field.dart#L61-L66); which was causing some undesired rebuilds.
The only caveat of this change, that the fields' names are considered magic strings that are shared between `fields` and `settingFromQueryGroup`.
> refactor: parse addon's setting from query param

- analysis_options.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
When decoding the query parameters of the device addon, a string-on-bool comparison is made for the frame, which is pretty weird. 
A linter rule was added to prevent that in the future.
> fix: use related type checks

- packages/widgetbook/lib/src/app/use_case_builder.dart
- packages/widgetbook/lib/src/app/workbench.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
Instead of rebuilding the use case with every knob getting registered, this PR aims at rebuilding the use case only once after the build method (i.e. all knobs have been registered but not built).
> refactor: build knobs once post build

- packages/widgetbook_core/CHANGELOG.md
- packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree.dart
Prevent `onNodeSelected` from being called if the node is already selected.
> fix(core): call `onNodeSelected` for unique nodes

- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/app.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/generators/tree_service.dart
- packages/widgetbook_generator/lib/instances/widgetbook_category_instance.dart
- packages/widgetbook_generator/lib/instances/widgetbook_folder_instance.dart
- packages/widgetbook_generator/lib/instances/widgetbook_widget_instance.dart
- packages/widgetbook_generator/test/src/instances/widgetbook_category_instance_test.dart
- packages/widgetbook_generator/test/src/instances/widgetbook_folder_instance_test.dart
The `foldersExpanded` and `widgetsExpanded` params were not working for the following reasons:
1. All `MultiChildNavigationNodeData` has `isInitiallyExpanded` defaulting to `true`.
2. `WidgetbookFolderInstance` and `WidgetbookComponentInstance` would only set `isInitiallyExpanded` if and only if the `isExpanded` param is `true`, so setting any of the above params would have no effect.
> refactor(annotation): remove `@App`'s non-working params

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/test/src/knobs/list_knob_test.dart
Adds support to select the initial list option from `list` knob
> feat: add `initialOption` to `list` knob

- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/build.yaml
- packages/widgetbook_generator/example/main.dart
- packages/widgetbook_generator/lib/builder.dart
- packages/widgetbook_generator/lib/generators/app_generator.dart
- widgetbook_for_widgetbook/lib/widgetbook.dart
Change extension from `.g.dart` to `.directories.g.dart` to avoid conflicts with other generators (e.g. `json_serializable`) that use the same extension.
> refactor(generator): change generated extension

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/widgetbook.dart
The new `listOrNull` knob is the nullable alternative of the `list` knob. This should be used if the options have a nullable value.
> feat: add `listOrNull` knob

- packages/widgetbook_cli/bin/api/widgetbook_http_client.dart
dio deprecated `DioError` in favor of `DioException`
> `DioError` is deprecated and shouldn't be used. Use `DioException` instead. This will be removed in 6.0.0.
> refactor(cli): use `DioException` instead of `DioError`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/fields/fields.dart
- packages/widgetbook/lib/src/fields/fields_composable.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/routing/widgetbook_shell.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/test/src/addons/common/custom_addon.dart
- packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
- packages/widgetbook/test/src/knobs/knob_helper.dart
The `FieldsComposable` is an interface for unifying how features that uses Fields as building blocks (i.e. Addons and Knobs) should behave. This lead to some breaking changes as follow:
| Class             | Old Method Name         | New Method Name       |
|-------------------|-------------------------|-----------------------|
| `WidgetbookAddon` | `settingFromQueryGroup` | `valueFromQueryGroup` |
| `WidgetbookAddon` | `buildSetting`          | `buildFields`         |
| `Knob`            | `build`                 | `buildFields`         |
> refactor: add `FieldsComposable`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/widgetbook_shell.dart
- packages/widgetbook/lib/src/settings/settings_panel.dart
- packages/widgetbook/lib/src/workbench/use_case_builder.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/test/src/app/settings/settings_panel_test.dart
- sandbox/lib/settings/settings_panel.widgetbook.dart
The following pattern was used in a lot of `Widget`s, which caused the UI to not reflect the actual `WidgetbookState`, because the `SomeWidget` will now have outdated values of `state` on some rebuilds.
```dart
// Before
@override
Widget build(BuildContext context) {
final state = WidgetbookState.of(context);
return SomeWidget(
child: state.someValue,
);
}
// After
@override
Widget build(BuildContext context) {  
return SomeWidget(
builder: (context) => WidgetbookState.of(context).someValue,
);
}
```
> fix: use fresh `context` for state

- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/fields/fields_composable.dart
- packages/widgetbook/lib/src/knobs/boolean_knob.dart
- packages/widgetbook/lib/src/knobs/color_knob.dart
- packages/widgetbook/lib/src/knobs/double_input_knob.dart
- packages/widgetbook/lib/src/knobs/double_slider_knob.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/src/knobs/string_knob.dart
Make use of `Field`'s `codec`s to decode the query groups inside `valueFromQueryGroup`, instead of duplicating the logic and doing the decoding logic manually. This is much less error-prune and and cleaner
```dart
// Before
@override
SomeSetting valueFromQueryGroup(Map<String, String> group) {
return SomeSetting(
foo: group['foo'] == 'true',
bar: list.firstWhereOrNull(
(item) => item?.name == group['bar'],
),
);
}
// After
@override
SomeSetting valueFromQueryGroup(Map<String, String> group) {
return SomeSetting(
foo: valueOf('foo', group),
bar: valueOf('bar', group),
);
}
```
> refactor: add `FieldsComposable.valueOf`

- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/fields/fields_composable.dart
- packages/widgetbook/lib/src/integrations/widgetbook_cloud_integration/widgetbook_cloud_integration.dart
- packages/widgetbook/lib/src/integrations/widgetbook_integration.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/src/workbench/use_case_builder.dart
Addons and Knobs are sent to Widgetbook Cloud via the `WidgetbookCloudIntegration` as follows:
```json
// Sent on initialization once
{
"addons": [
{
"name": "Addon Name",
"group": "addon-name",
"fields": [
{
"name": "field-name",
"type": "..."
// ...
}
]
}
]
}
// Sent after knobs get registered
{
"knobs": [
{
"name": "Knob Name",
"group": "knobs",
"nullable": false,
"fields": [
{
"name": "field-name",
"type": "..."
// ...
}
]
}
]
}
```
> feat: send fields composables to cloud

- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/fields/boolean_field.dart
- packages/widgetbook/lib/src/fields/color_field.dart
- packages/widgetbook/lib/src/fields/double_input_field.dart
- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/fields/fields_composable.dart
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/lib/src/fields/string_field.dart
- packages/widgetbook/lib/src/knobs/boolean_knob.dart
- packages/widgetbook/lib/src/knobs/color_knob.dart
- packages/widgetbook/lib/src/knobs/double_input_knob.dart
- packages/widgetbook/lib/src/knobs/double_slider_knob.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/src/knobs/string_knob.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
Instead of passing `group` to each `Field`, a new property called `groupName` is added to `FieldsComposable`, this value is passed to all `fields`.
> refactor: move `group` to `FieldsComposable`

- packages/widgetbook/lib/src/routing/app_route_config.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
When Widgetbook started on web, the URL would be initially something like this `/?path`, that's because the `path` had an initial value of an empty string.
> fix: remove empty `path` from initial route

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/theme_addon/cupertino_theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/material_theme_addon.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
The `Scaffold` around the `UseCaseBuilder` has the responsibility of making the `Workbench`'s background color match the current theme. But the `Scaffold` filled the whole `Workbench` area, causing issues like #787.
This PR adds a `ColoredBox` iniside the `ThemeAddon`s, to allow alignment later on.
> fix: replace `Scaffold` with `ColoredBox`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/state/default_app_builders.dart
After removing `Scaffold` in #789, the widgets tree lacked the `Material` widget.
This PR aims at re-adding the `Material` widget through the default `appBuilder` of `Widgetbook.material`.
> fix: add `Material` to `materialAppBuilder`

- packages/widgetbook/lib/src/workbench/workbench.dart
After removing `Scaffold` in #789, the `UseCaseBuilder` was expanding to the whole size of `Workbench`, which caused some widets like `DropdownMenu` to misbehave as show below.
| Before | After |
| :-----: |  :---: |
| ![before](https://github.com/widgetbook/widgetbook/assets/41103290/bf8d604a-2164-40ee-916d-68f68fed12dd) | ![after](https://github.com/widgetbook/widgetbook/assets/41103290/3b239d48-6d96-49b6-b45a-3bb151c13267) |
> fix: loosen `UseCaseBuilder` constraints

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/widgetbook.dart
Initial routes can be used to pick the home page that is used on first launch as follows:
```dart
Widgetbook(
initialRoute: '?path=foo-bar',
// ...
)
```
> feat: add `initialRoute`

- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/lib/src/themes.dart
- packages/widgetbook/test/src/knobs/double_slider_knob_test.dart
Give the `DoubleSliderField` some improvements:
1. Remove leading thumb space.
2. Round labels to 2 digit points.
3. Adjust Flex ratios.
> fix: prevent `DoubleSliderField` from overflow

- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- sandbox/lib/widgetbook.dart
When device frame is active, the background area used to match the `ThemeAddon`'s active theme.
This PR uses the Widgetbook theme for the background color.
| Before | After |
| :---: |  :---: |
| ![Screenshot 2023-06-30 at 6 42 31 PM](https://github.com/widgetbook/widgetbook/assets/41103290/aabaaa59-a53f-4446-af8c-687bcc52b43c) | ![Screenshot 2023-06-30 at 6 41 07 PM](https://github.com/widgetbook/widgetbook/assets/41103290/26102dac-1974-4b81-9fb4-ac49c80a0c95) |
> refactor: add background color to device frame

- docs/addons/overview.mdx
- docs/getting-started/setup.mdx
Renames all instances of `widgetbook.g.dart` to `widgetbook.directories.g.dart` within the documentation. 
- closes #807
> docs: corrected the name of the file created by build_runner

- docs/getting-started/setup.mdx
- removes the `appBuilder` from the material example as this will remove the `MaterialApp` widget from the tree. In my opinion, this is required to display Material themes properly.
> docs: remove `appBuilder` from material example

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/workbench/use_case_builder.dart
While working on conditional addon availability (https://github.com/widgetbook/widgetbook/issues/811) I've encountered an assertion violation in `UseCaseBuilder` when the addon changes its behavior. And actually there's an existing issue logged about this already
```
The following assertion was thrown during a scheduler callback:
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
packages/flutter/src/widgets/framework.dart 951:9                                 <fn> …
```
> fix: ensure widget is mounted on change

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/list_knob.dart
Use explicit type casting instead of implicit one.
> fix: correct `listOrNull` knob type cast

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/pubspec.yaml
When a use-case file exists outside the `lib` directory, the import statement starts with `asset:` instead of `package:`, which causes the use-case method to not be imported properly. This usually happens with users who define their use-cases inside `test` or `widgetbook` folders.
To fix this issue, the user must move the `widgetbook.dart` file to the folder containing the use-cases' definition, and all `asset:` imports will be converted to relative ones.
> fix(generator): resolve "asset:" imports

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/directories/widgetbook_use_case.dart
The `AlignmentAddon` was introduced in #798, which is available in version 3.1.0, and it serves as a better alternative for `WidgetbookUseCase.center`.
> refactor: deprecate `WidgetbookUseCase.center`

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/generators/use_case_resolver.dart
- packages/widgetbook_generator/pubspec.yaml
The `analyzer` cannot provide the actual paths of files, instead it returns the path as `{package_name}/lib/...`, which can be mismatching when the `package_name` is **not the actual directory** name holding the package.
This mismatch leads into another mismatch within the CLI, when it's comparing **the component path** and the **git diff pathes**, which leads to missing the component changes on Widgetbook Cloud.
> fix(generator): resolve local packages paths

- docs/knobs/overview.mdx
According to this PR https://github.com/widgetbook/widgetbook/pull/741/files
we need to add listOrNull to the doc. 
- [ x] I signed the [CLA].
- [ x] I updated/added relevant documentation (doc comments with `///`).
> docs: add `listOrNull` to knobs list

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
Support both v5 and v6 of `package:analyzer`.
> refactor(generator): support analyzer 6.x

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/instances/list_instance.dart
- packages/widgetbook_generator/test/src/instances/list_instance_test.dart
Disclaimer:
This PR might be breaking because the directories type changed from `MultiChildNavigationData` to `WidgetbookNode` in #833
> fix(generator): add type to `directories` list

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
Since the next version of `widgetbook_generator` will only work with the next version of `widgetbook` (due to #836), a version constraint is added to enforce the version dependency.
> chore(generator): enforce `widgetbook` min version

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/navigation/widgets/search_field.dart
- packages/widgetbook/lib/src/themes.dart
Match `DropdownMenu` theme with `TextField`.
| Before | After |
|--------|-------|
| <img width="1512" alt="Before" src="https://github.com/widgetbook/widgetbook/assets/41103290/f058023b-b5a7-4fd9-b834-411d2333334e"> | <img width="1512" alt="After" src="https://github.com/widgetbook/widgetbook/assets/41103290/a37e4dbc-b5c2-4749-a09f-b7cdf4f8ca47"> |
> refactor: update `DropdownMenu` theme

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/app_route_config.dart
- packages/widgetbook/lib/src/routing/app_route_parser.dart
- packages/widgetbook/lib/src/routing/app_router.dart
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/test/src/routing/app_route_config_test.dart
- packages/widgetbook/test/src/routing/app_router_delegate_test.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
This PR makes Widgetbook work with **Flutter 3.13.0**, by:
1. Ignoring* the [deprecated](https://docs.flutter.dev/release/breaking-changes/route-information-uri) member `RouteInformation.location`.
1. Resolving the type-conflict happened from changing `RouteInformation.location` type from `String?` (in < 3.13.0) to `String` (in 3.13.0).
*We cannot fully migrate to `RouteInformation.uri` because it will not be backwards compatible with all Flutter versions prior to 3.13.0. That's why we do a partial migration by converting `AppRouteConfig.location` to `AppRouteConfig.uri`, to make it easier in the future to do the full migration once we drop support to old Flutter versions.
> refactor: support Flutter 3.13.0

- .github/workflows/_package.yml
It's all about equality 🌟
Treat infos and warnings the same.
> ci: make analyzer's infos fatal

- packages/widgetbook/lib/src/knobs/boolean_knob.dart
- packages/widgetbook/lib/src/knobs/builders/double_knobs_builder.dart
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/double_input_knob.dart
- packages/widgetbook/lib/src/knobs/double_slider_knob.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/src/knobs/string_knob.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/widgetbook.dart
- packages/widgetbook/test/src/knobs/boolean_knob_test.dart
- packages/widgetbook/test/src/knobs/knob_test.dart
- packages/widgetbook/test/src/knobs/string_knob_test.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
For each `X` nullable knob we had two classes:
1. `XKnob`
2. `XOrNullKnob`
The two classes shared almost all code, that's why it was a good idea to merge them into one that is controlled by 1 parameter called `isNullable`.
> refactor: remove *-`OrNullKnob` classes

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_setting.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/none_device.dart
- packages/widgetbook/test/src/addons/device_frame_addon_test.dart
The `null` device caused some trouble with the `Field` system, that will take a while to fix properly. This is a temporary workaround that fixes the issue when `DeviceFrameAddon` had a `initialValue`, it could not be set back to `None`.
> refactor: replace `null` device with `NoneDevice`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/app_route_config.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/test/src/routing/app_route_config_test.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
This issue resulted after merging #782, causing URL to be
`/#/?device={name:None}&path=navigation/default` (notice `device` appears before `path`)
> fix: make `path` first query param

- packages/widgetbook_generator/lib/code/refer.dart
- packages/widgetbook_generator/lib/code/resolver_allocator.dart
- packages/widgetbook_generator/lib/code/widgetbook_component_instance.dart
- packages/widgetbook_generator/lib/code/widgetbook_folder_instance.dart
- packages/widgetbook_generator/lib/code/widgetbook_instance.dart
- packages/widgetbook_generator/lib/code/widgetbook_use_case_instance.dart
- packages/widgetbook_generator/lib/generators/app_generator.dart
- packages/widgetbook_generator/lib/tree/tree_node.dart
- packages/widgetbook_generator/test/src/code/refer_test.dart
- packages/widgetbook_generator/test/src/code/resolver_allocator_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_component_instance_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_folder_instance_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_instance_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_use_case_instance_test.dart
Instead of passing down `baseDir` to all `WidgetbookInstance`s, a single `ResolverAllocator` is used to resolve imports directly from the `DartEmitter`.
> refactor(generator): create `ResolverAllocator`

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/code/resolver_allocator.dart
When two use-cases have the same function name (e.g. `deafultUseCase(BuildContext context)`), then the generated file will have imports collision. 
This PR adds prefixing to all imports to avoid that collision.
> fix(generator): apply imports prefixing

- docs/getting-started/components.mdx
Adding a reference to the mocking page from the component page, as it's in the middle of the getting started and may help developer 
- [x ] I signed the [CLA].
- [ x] I updated/added relevant documentation (doc comments with `///`).
> docs: add mocking page reference to component page

- docs.json
- docs/addons/use-case-builder-addon.mdx
- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/addons.dart
- packages/widgetbook/lib/src/addons/use_case_builder_addon/addon.dart
- packages/widgetbook/lib/src/addons/use_case_builder_addon/use_case_builder_addon.dart
- packages/widgetbook/test/src/addons/use_case_builder_addon_test.dart
- sandbox/lib/widgetbook.dart
Wrap all use-cases in a widget on the go, without the need to create a custom addon.
```dart
UseCaseBuilderAddon(
name: 'Red',
builder: (context, child) => ColoredBox(
color: Colors.red,
child: child,
),
)
```
> feat: add use-case builder addon

- packages/widgetbook/lib/src/settings/knob_property.dart
The field `trailing` was never used.
> refactor: remove `trailing` from `KnobProperty`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
This new method can edit a query field within a query group.
It can be used for bi-directional knob updates as follow:
```dart
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart';
@UseCase(name: 'Default', type: CheckboxListTile)
Widget checkBoxTileUseCase(BuildContext context) {
return CheckboxListTile(
title: const Text('Title'),
value: context.knobs.boolean(label: 'Checkbox Knob'),
onChanged: (value) {
WidgetbookState.of(context).updateQueryField(
group: 'knobs',
field: 'Checkbox Knob',
value: '$value',
);
},
);
}
```
> feat: add `updateQueryField` to state

- docs/getting-started/components.mdx
Improve green container example by adding a SizedBox child. Without a child nothing shows up when running widgetbook.
- running widgetbook from the exmaple, nothing shows up 
> docs: fix getting started example

- .github/workflows/_package.yml
The following error was thrown while running `apt-get install webp`
```
The following additional packages will be installed:
freeglut3
The following NEW packages will be installed:
freeglut3 webp
0 upgraded, 2 newly installed, 0 to remove and 28 not upgraded.
Need to get 160 kB of archives.
After this operation, 632 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 freeglut3 amd64 2.8.1-6 [74.0 kB]
Ign:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 webp amd64 1.2.2-2ubuntu0.22.04.1
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 webp amd64 1.2.2-2ubuntu0.22.04.1
Ign:3 http://security.ubuntu.com/ubuntu jammy-updates/universe amd64 webp …
```
> ci: fix webp

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/knobs_registry.dart
`MapBase` can only be used as a mixin with Dart v3,
while `MapMixin` works with both Dart v2 and v3.
> fix: use `MapMixin` instead of `MapBase`

- .gitignore
- packages/widgetbook_cli/bin/helpers/version.dart
To make the CLI easily usable directly from GitHub as a source, we are checking in the only generated file.
> refactor(cli): check-in `version.dart`

- packages/widgetbook_cli/pubspec.yaml
Package `test` ended up in `dependencies` not `dev_dependencies` for some reason.
Now we are putting it back to where it belongs.
> chore(cli): move `test` to `dev_dependencies`

- packages/widgetbook_cli/bin/ci_parser/azure_parser.dart
- packages/widgetbook_cli/bin/ci_parser/bitbucket_parser.dart
- packages/widgetbook_cli/bin/ci_parser/ci_parser.dart
- packages/widgetbook_cli/bin/ci_parser/ci_parser_runner.dart
- packages/widgetbook_cli/bin/ci_parser/codemagic_parser.dart
- packages/widgetbook_cli/bin/ci_parser/github_parser.dart
- packages/widgetbook_cli/bin/ci_parser/gitlab_parser.dart
- packages/widgetbook_cli/bin/ci_parser/platform_wrapper.dart
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_cli/test/ci_parser/azure_parser_test.dart
- packages/widgetbook_cli/test/ci_parser/bitbucket_parser_test.dart
- packages/widgetbook_cli/test/ci_parser/ci_parser_runner_test.dart
- packages/widgetbook_cli/test/ci_parser/github_parser_test.dart
- packages/widgetbook_cli/test/ci_parser/gitlab_parser_test.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
Use [`platform`](https://pub.dev/packages/platform) package to mock `dart:io`'s `Platform` instead of using `PlatformWrapper`.
> refactor(cli): remove `PlatformWrapper`

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/std/stdin_wrapper.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/mocks/command_mocks.dart
Use [`IOOverrides`](https://api.flutter.dev/flutter/dart-io/IOOverrides-class.html) to mock `Stdin` instead of `StdinWrapper`.
> refactor(cli): remove `StdInWrapper`

- .vscode/launch.json
- docs/widgetbook-cli/overview.mdx
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/README.md
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/models/publish_args.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
- packages/widgetbook_cli/test/helpers/test_data.dart
The `--git-provider` option was redundant as only GitHub was supported as a provider, and passing different values have no effect.
> refactor(cli): remove `--git-provider` option

- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
The old `publishBuilds` method was a big function that did a lot of logic, so it has been renamed to `publish` and split into two methods, `publishBuild` and `publishReview`, for better maintainability.
> refactor(cli): split `publish` method

- docs/widgetbook-cloud/signup.mdx
You can now sign up for Widgetbook Cloud using this [link](https://www.widgetbook.io/plans).
> docs: update sign-up link

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/themes.dart
- packages/widgetbook/lib/src/widgetbook.dart
Adds light color scheme and enables automatic system theme-based support for the light theme.
#905 
> feat: add light theme

- docs/widgetbook-cli/overview.mdx
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/README.md
- packages/widgetbook_cli/bin/commands/publish.dart
- packages/widgetbook_cli/test/commands/publish_test.dart
Following down the path of this option, it lead to nowhere.
Thus, it's going down until we add it properly (if needed).
> refactor(cli): remove `--base-commit` option

- CONTRIBUTING.md
- docs/contribution/get-started.mdx
- docs/contribution/workflow.mdx
Fixed Getting started URL and Synchronize Your Fork URL
*Updated 2 URLs in th docs and read me files since the original ones were navigating to 404.*
> docs: fix contribution URLs

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
fixed navigation panel selection on page refresh
> fix: maintain navigation panel state on reload

- packages/widgetbook_cli/bin/commands/upgrade.dart
- packages/widgetbook_cli/bin/core/cli_runner.dart
- packages/widgetbook_cli/bin/helpers/helpers.dart
- packages/widgetbook_cli/bin/helpers/metadata.dart
- packages/widgetbook_cli/bin/helpers/version.dart
- packages/widgetbook_cli/bin/metadata.dart
- packages/widgetbook_cli/build.yaml
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_cli/test/commands/upgrade_test.dart
- packages/widgetbook_cli/test/core/cli_runner_test.dart
- packages/widgetbook_cli/test/metadata_test.dart
Manually update `packageVersion` instead of using code generation.
A test was added to make sure that the version is always up to date with `pubspec.yaml`.
> refactor(cli): remove `build_version`

- .github/workflows/_package.yml
- .github/workflows/_upload.yml
- .github/workflows/common.yml
- melos.yaml
Packages no longer require code generation, so `MELOS_FILTER` is no longer needed.
Code generation steps were optimized for faster run time.
> ci: remove `MELOS_FILTERS`

- docs/contribution/get-started.mdx
- docs/contribution/ways-to-contribute.mdx
- docs/contribution/workflow.mdx
This PR fixes a small handful of broken links in the contribution documentation.
I am guilty, there is no issue for this. I just noticed these while following the contribution docs.
N/A
> docs: fix contribution links

- packages/widgetbook_cli/lib/src/commands/publish.dart
- packages/widgetbook_cli/lib/src/utils/use_case_reader.dart
`UseCaseReader.compare` was not working properly because of:
1. Files were filtered using `takeWhile` instead of `where`.
1. `hasChanged` always returned `false` for added and deleted files because their `base`/`ref` are null.
> fix(cli): include added/deleted files in review

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/models/changed_use_case.dart
- packages/widgetbook_cli/lib/src/models/use_case_metadata.dart
In #992, the `name` property was messed up with `useCaseName`. So the use-case function name was sent instead of the actual use-case name.
> fix(cli): send `useCaseName` in `ChangedUseCase`

- packages/widgetbook_cli/lib/src/api/api.dart
- packages/widgetbook_cli/lib/src/api/models/versions_metadata.dart
- packages/widgetbook_cli/lib/src/api/widgetbook_http_client.dart
- packages/widgetbook_cli/lib/src/commands/publish.dart
- packages/widgetbook_cli/lib/src/commands/publish_args.dart
- packages/widgetbook_cli/lib/src/git/git.dart
- packages/widgetbook_cli/lib/src/git/repository.dart
- packages/widgetbook_cli/lib/src/utils/executable_manager.dart
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_cli/test/src/commands/publish_test.dart
The following versions are being sent to Widgetbook Cloud when a review or build is published:
1. Flutter version
1. `widgetbook` version
1. `widgetbook_cli` version
1. `widgetbook_annotation` version
1. `widgetbook_generator` version
The versions are used to toggle features on/off depending on compatibility.
> feat(cli): send versions with requests

- examples/full_example/lib/widgetbook.generator.directories.g.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/icons/resolve_icon.dart
- packages/widgetbook/lib/src/navigation/nodes/nodes.dart
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_leaf_component.dart
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_node.dart
- packages/widgetbook/lib/src/navigation/widgets/navigation_tree_node.dart
- packages/widgetbook/lib/src/navigation/widgets/navigation_tree_tile.dart
- packages/widgetbook/test/src/navigation/widgets/navigation_tree_item_test.dart
- packages/widgetbook/test/src/navigation/widgets/navigation_tree_node_test.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/code/widgetbook_instance.dart
- packages/widgetbook_generator/lib/src/code/widgetbook_leaf_component_instance.dart
- packages/widgetbook_generator/lib/widgetbook_generator.dart
- packages/widgetbook_generator/test/src/code/widgetbook_folder_instance_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_instance_test.dart
- packages/widgetbook_generator/test/src/code/widgetbook_leaf_component_instance_test.dart
The new `WidgetbookLeafComponent` is a more compact version of `WidgetbookComponent` for the cases when the component only have a single use-case. This makes the navigation tree much more cleaner.
> feat: add `WidgetbookLeafComponent`

- packages/widgetbook/lib/src/fields/num_input_field.dart
- packages/widgetbook/lib/src/fields/num_slider_field.dart
An assertion was thrown when a `DoubleXField` used `as` on `0` because `T` is `double` and `0` is `int`.
> fix: use type-based default values for num fields

- analysis_options.yaml
- packages/widgetbook/lib/src/addons/grid_addon/grid_addon.dart
- packages/widgetbook/lib/src/addons/inspector_addon/inspector_addon.dart
- packages/widgetbook/lib/src/addons/zoom_addon/zoom_addon.dart
- packages/widgetbook/lib/src/fields/duration_field.dart
- packages/widgetbook/lib/src/fields/num_input_field.dart
Add [`avoid_renaming_method_parameters`](https://dart.dev/tools/linter-rules/avoid_renaming_method_parameters) rule.
> chore: add `avoid_renaming_method_parameters` lint rule

- examples/full_example/lib/customs/custom_addon.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/accessibility_addon/accessibility_addon.dart
- packages/widgetbook/lib/src/addons/alignment_addon/alignment_addon.dart
- packages/widgetbook/lib/src/addons/builder_addon/builder_addon.dart
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/grid_addon/grid_addon.dart
- packages/widgetbook/lib/src/addons/inspector_addon/inspector_addon.dart
- packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
- packages/widgetbook/lib/src/addons/time_dilation_addon/time_dilation_addon.dart
- packages/widgetbook/lib/src/addons/zoom_addon/zoom_addon.dart
- packages/widgetbook/test/src/addons/inspector_addon_test.dart
- packages/widgetbook/test/src/addons/multi_addon_builder_test.dart
- packages/widgetbook/test/src/addons/zoom_addon_test.dart
Some addons have no setting, for example `InspectorAddon`. The `initialSetting` field does not make sense for these type of addons, so we will be leaving up to the implementer to add this kind of filed to their custom addon.
```dart
class CustomAddon extends WidgetbookAddon<int> {
CustomAddon(int value)
: super(
name: 'Addon',
initialSetting: value,
);
// Use `initialSetting`...
} 
```
```dart
class CustomAddon extends WidgetbookAddon<int> {
CustomAddon(this.value)
: super(
name: 'Addon',
);
final int value;
// Use `value`...
} 
```
> refactor: deprecate `WidgetbookAddon.initialSetting`

- docs/knobs/custom-knob.mdx
- examples/full_example/lib/customs/custom_knob.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/boolean_field.dart
- packages/widgetbook/lib/src/fields/color_field/color_field.dart
- packages/widgetbook/lib/src/fields/date_time_field.dart
- packages/widgetbook/lib/src/fields/double_input_field.dart
- packages/widgetbook/lib/src/fields/double_slider_field.dart
- packages/widgetbook/lib/src/fields/duration_field.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/fields/int_input_field.dart
- packages/widgetbook/lib/src/fields/int_slider_field.dart
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/lib/src/fields/num_input_field.dart
- packages/widgetbook/lib/src/fields/num_slider_field.dart
- packages/widgetbook/lib/src/fields/string_field.dart
- packages/widgetbook/lib/src/knobs/boolean_knob.dart
- packages/widgetbook/lib/src/knobs/color_knob.dart
- packages/widgetbook/lib/src/knobs/date_time_knob.dart
- packages/widgetbook/lib/src/knobs/double_input_knob.dart
- packages/widgetbook/lib/src/knobs/double_slider_knob.dart
- packages/widgetbook/lib/src/knobs/duration_knob.dart
- packages/widgetbook/lib/src/knobs/int_input_knob.dart
- packages/widgetbook/lib/src/knobs/int_slider_knob.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/src/knobs/string_knob.dart
- packages/widgetbook/test/src/fields/field_test.dart
The `onChanged` property of `Field` allow users to implement anti-patterns that will not work with Widgetbook Cloud. This is because Widgetbook Cloud is implemented in React and the way it renders these `Field`s is using the JSON shared from `Field.toFullJson`, which cannot decode non-primitive types like `onChanged`.
To prevent this kind of anti-pattern, `onChanged` is deprecated to warn about future removals.
> refactor: deprecate `Field.onChanged`

- docs/knobs/custom-knob.mdx
- examples/full_example/lib/customs/custom_knob.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/boolean_knob.dart
- packages/widgetbook/lib/src/knobs/builders/double_knobs_builder.dart
- packages/widgetbook/lib/src/knobs/builders/int_knobs_builder.dart
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/color_knob.dart
- packages/widgetbook/lib/src/knobs/date_time_knob.dart
- packages/widgetbook/lib/src/knobs/double_input_knob.dart
- packages/widgetbook/lib/src/knobs/double_slider_knob.dart
- packages/widgetbook/lib/src/knobs/duration_knob.dart
- packages/widgetbook/lib/src/knobs/int_input_knob.dart
- packages/widgetbook/lib/src/knobs/int_slider_knob.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/knobs/knobs_registry.dart
- packages/widgetbook/lib/src/knobs/list_knob.dart
- packages/widgetbook/lib/src/knobs/string_knob.dart
- packages/widgetbook/test/src/integrations/widgetbook_cloud_integration_test.dart
- packages/widgetbook/test/src/knobs/double_input_knob_test.dart
- packages/widgetbook/test/src/knobs/double_slider_knob_test.dart
- packages/widgetbook/test/src/knobs/duration_knob_test.dart
- packages/widgetbook/test/src/knobs/int_input_knob_test.dart
- packages/widgetbook/test/src/knobs/int_slider_knob_test.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
The `Knob`'s `value` was only used as an `initialValue` for `Field`s. It has no other purposes. Even calls to `KnobRegistry.updateValue` were redundant due to the fact that `register` uses `Knob.valueFromQueryGroup` and not `Knob.value`.
To make things more clear, we will be deprecating `Knob.value` in favor of `Knob.initialValue`. In addition, `KnobRegistry.updateValue` is deprecated as well, and currently it's a no-op.
> refactor: replace knobs `value` with `initialValue`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/test/src/knobs/boolean_knob_test.dart
Match other `orNull` knobs' `initialValue`.
> fix: change `booleanOrNull`'s `initialValue` to null

- docs/knobs/overview.mdx
- examples/knobs_example/lib/widgetbook.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/lib/src/knobs/color_knob.dart
The twin of `color` knob is here.
> feat: add `colorOrNull` knob

- packages/widgetbook/lib/src/fields/color_field/color_picker.dart
If the settings side panel got too small, the `ColorField` will throw an exception, preventing all knobs from being properly rendered. A workaround would be to use `Wrap` instead of `Row`.
> fix: make `ColorField` responsive

- examples/full_example/lib/components/stepped_counter.dart
- examples/full_example/lib/widgetbook.generator.directories.g.dart
An example of preserving `StatefulWidget` state as proposed in #788
> chore: add `StatefulWidget` example

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/theme_addon/cupertino_theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/material_theme_addon.dart
In #789, `Scaffold` was replaced by `ColoredBox`, the `Scaffold` widget used to add the `DefaultTextStyle` widget to the tree, but after that change, the `DefaultTextStyle` should be added via the `ThemeAddon`s.
> fix: add `DefaultTextStyle` to `ThemeAddon`s

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/next/story.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- sandbox/lib/next/types_table.stories.dart
The `setup` parameter is used to wrap stories with some widgets before they get rendered. This could be useful for mocking.
> feat: add `setup` to `Story`

- docs/next/sam.mdx
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/nodes/widgetbook_use_case.dart
- packages/widgetbook/lib/src/next/args/arg.dart
- packages/widgetbook/lib/src/next/args/builder_arg.dart
- packages/widgetbook/lib/src/next/args/story_args.dart
- packages/widgetbook/lib/src/next/component.dart
- packages/widgetbook/lib/src/next/meta.dart
- packages/widgetbook/lib/src/next/scenario.dart
- packages/widgetbook/lib/src/next/story.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/next/args_class_builder.dart
- packages/widgetbook_generator/lib/src/next/component_builder.dart
- packages/widgetbook_generator/lib/src/next/components_builder.dart
- packages/widgetbook_generator/lib/src/next/scenario_typedef_builder.dart
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- packages/widgetbook_generator/lib/src/next/story_generator.dart
- sandbox/lib/next/label_badge.dart
- sandbox/lib/next/label_badge.stories.dart
Args usually match the Widget's constructor, but in some cases users want to customize that.
```dart
// 1. Define the custom args class
class CustomInputs {
CustomInputs({
required this.number,
});
final int number;
}
// 2. Use `MetaWithArgs` instead of `Meta`
final meta = MetaWithArgs<CoolWidget, CustomInputs>();
final $Default = CoolWidgetStory(
name: 'Default',
// 3. Specify how to convert the args (CustomInputsArgs) to a widget (CoolWidget)
argsBuilder: (context, args) => CoolWidget(
text: args.number.resolve(context).toString(),
),
);
```
> feat: support custom args

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/next/story.dart
- sandbox/lib/next/types_table.stories.dart
Allowing access to `args` in `setup` method can be beneficial for cases that the setup method is used to inject a `Provider` that needs those `args`.
> refactor: add `args` to `setup`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/inspector_addon/inspector_addon.dart
- packages/widgetbook/test/src/addons/inspector_addon_test.dart
By passing `enabled` to the `Inspector` widget we ensure that the inspector is properly toggled for release builds. See issue below for further details.
- https://github.com/widgetbook/widgetbook/issues/1085
For the following screenshots I ran `flutter build web` and then ran the build with `dhhtpd`.
First is before change, and second is with my change, where you can see the `Inspector` is now shown.
> fix: enable `InspectorAddon` on release builds

- packages/widgetbook/lib/src/next/meta.dart
- packages/widgetbook_generator/lib/src/next/component_builder.dart
A fallback path is now generated if the `Meta.path` parameter is not specified.
> feat: generate component default path

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/double_input_field.dart
> fix: update `DoubleInputField` regex

- docs/addons/theme-addon.mdx
- docs/cookbook/custom-theme.mdx
- docs/getting-started/complete-example.mdx
- docs/getting-started/setup.mdx
- docs/getting-started/structure.mdx
- docs/knobs/example.mdx
- docs/monorepo/getting-started.mdx
- docs/widgetbook-cloud/reviews.mdx
A very minor improvement on the getting started docs to make the snippet in the setup docs to use super parameters.
> docs: use `super.key`

- packages/widgetbook_cli/lib/src/core/environment.dart
Only affects the `widgetbook_staging` and `widgetbook_debug` binaries.
The `widgetbook` binary is not affected.
> fix(cli): use staging `appUrl` for non-prod envs

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/core/args_class_builder.dart
- packages/widgetbook_generator/lib/src/core/component_builder.dart
- packages/widgetbook_generator/lib/src/core/extensions.dart
- packages/widgetbook_generator/lib/src/core/scenario_typedef_builder.dart
- packages/widgetbook_generator/lib/src/core/story_class_builder.dart
- sandbox/lib/[sam]/generic_num.dart
- sandbox/lib/[sam]/generic_num.stories.dart
- sandbox/lib/[sam]/generic_text.dart
- sandbox/lib/[sam]/generic_text.stories.dart
Add support for generic widgets.
```dart
// generic_text.dart
class GenericText<T> extends StatelessWidget {
const GenericText({
super.key,
required this.value,
});
final T value;
@override
Widget build(BuildContext context) {
return Text(
'[$T] $value',
);
}
}
```
```dart
// generic_text.stories.dart
final meta = Meta<GenericText>();
final $IntStory = GenericTextStory<int>(
args: GenericTextArgs.fixed(
value: 0,
),
);
final $BoolStory = GenericTextStory<bool>(
args: GenericTextArgs.fixed(
value: false,
),
);
```
> feat(generator): support generic widgets

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/core/story_class_builder.dart
- packages/widgetbook_generator/lib/src/core/story_generator.dart
- sandbox/lib/[sam]/generic_num.stories.dart
- sandbox/lib/[sam]/label_badge.stories.dart
The default `setup` and `argsBuilder` were added in #1130, but to add support for these functions with generic widgets, they had to be renamed  to `$setup` and `$argsBuilder` because:
1. Tear-off of generic functions is not allowed in the constructor.
1.  The name `argsBuilder` cannot be used in `super` initializer due to shadowing.
> refactor(generator): add `$` prefix to defaults

- docs/getting-started/install.mdx
Remove extra whitespace in install documents
- #1143 
There is an extra space here.
> docs: remove extra space

- packages/widgetbook/lib/src/addons/theme_addon/cupertino_theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/material_theme_addon.dart
- packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
Updates the documentation for `ThemeAddon` and `MaterialThemeAddon`.
Changes:
- Adds information to `ThemeAddon` regarding the `initialTheme` member.
- Adds the same information to `MaterialThemeAddon` regarding the `initialTheme` member
- Updates the `ThemeAddon` class documentation about `themeBuilder` to comply with Effective Dart ([DO separate the first sentence of a doc comment into its own paragraph](https://dart.dev/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph))
~- [ ] I listed at least one issue that this PR fixes in the description above.~
~- [ ] I added new tests to check the change I am making].~
[Discord]: …
> docs(widgetbook): improve `ThemeAddon` doc comments

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/test/src/fields/list_field_test.dart
The DropdownMenu has search enabled, which allows users to type any input. If the user types something that doesn't match an existing item, value is null, leading to a null pointer issue.
The test is a little finicky, this behaviour only happens on Desktops, or when the `DropdownMenu` is created with `requestFocusOnTap: true`. IMHO it might be better to allow requestFocusOnTap to be set in the `ListField`, but that's. more invasive code change, so instead I used a TargetPlatformVariant.
Fixes https://github.com/widgetbook/widgetbook/issues/1151
> fix: guard `list` knob against null search values

- docs/widgetbook-cloud/hosting.mdx
Add a CI guide to [Widgetbook Cloud Hosting](https://docs.widgetbook.io/widgetbook-cloud/hosting).
Preview can be found [here](https://docs.widgetbook.io/~1161/widgetbook-cloud/hosting).
> docs: add ci to cloud hosting

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/field_codec.dart
- packages/widgetbook/test/src/fields/field_codec_test.dart
Using colon in label name of a knobs presents side effects. When changing the knob value, the UI is not refreshed.
This is caused by the way `Fields` are encoded/decoded. The current PR enables to fix the bug by encoding the field label. 
#1164
> fix: encode/decode fields labels to allow ':'

- docs/addons/custom-addon.mdx
This PR updates the docs adjusting to the deprecation of `WidgetbookAddon.initialSetting`.
\-
\-
> docs: remove `initialSetting` from custom addons

- docs/guides/customization.mdx
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/build.yaml
- packages/widgetbook_generator/lib/builder.dart
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
- packages/widgetbook_generator/lib/src/models/nav_path_mode.dart
- sandbox/build.yaml
The new `nav_path_mode` option allow to globally customize the behavior of navigation path generation.
| Option Value          | Navigation Path Based on                                           |
| :-------------------- | :----------------------------------------------------------------- |
| `component` (default) | The component _(i.e. Widget)_ file.                                |
| `use-case`            | The use-case file _(i.e. where the `@UseCase` annotation is used)_ |
To use the new option, add the following snippet to your `build.yaml` file:
```yaml
targets:
$default:
builders:
widgetbook_generator:use_case_builder:
options:
nav_path_mode: use-case
```
> feat(generator): add `nav_path_mode` option

- docs/telemetry.mdx
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/telemetry/telemetry_reporter.dart
- packages/widgetbook_generator/lib/src/telemetry/usage_report.dart
- packages/widgetbook_generator/test/src/telemetry/usage_report_test.dart
Since all projects are now named `widgetbook_workspace`, we need another identifier for projects. So starting from the next version of the generator, we will be reporting the SHA of the first commit in the repository to use it as a project identifier.
> refactor(generator): add `project_id` to telemetry

- .github/workflows/_package.yml
Since [`pana` v0.22.04](https://pub.dev/packages/pana/changelog#0224), the `pub downgrade` is checked, which might make the `check-min-version` job obsolete at first glance. But in fact, this job is still useful as it checks Flutter's minimum version itself, and not just the dependencies, making our packages more backwards compatible.
> ci: check analysis on min version

- docs/addons/accessibility-addon.mdx
The material import is unused in the `accessibility_addon.dart` file.
N/A
N/A
> docs: remove unused import in `AccessibilityAddon` guide

- docs.json
docs.page technically should accept a theme value of a hex code starting with a #
> docs: fix theme hex

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/next/addons/device_frame_addon.dart
- packages/widgetbook/test/src/addons/device_frame_addon_test.dart
Include a `Navigator` inside the `DeviceFrameAddon` to be used for popup routes (e.g. dialogs and bottom sheets).
> fix: show popup routes within device frame

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/date_time_field.dart
- packages/widgetbook/lib/src/fields/field_codec.dart
- packages/widgetbook/lib/src/fields/string_field.dart
- packages/widgetbook/test/helper/tester_extension.dart
- packages/widgetbook/test/src/fields/field_codec_test.dart
- packages/widgetbook/test/src/fields/string_field_test.dart
Previously, we were only encoding/decoding only `StringField` and `DateField` because they might contain some reserved characters like commas or colons. But this issue might happen with other fields as well, for example the `ListField` in #1179.
The encoding/decoding was lifted up to be done when grouping fields in `encodeQueryGroup`/`decodeQueryGroup`, to take effect on all fields.
> fix: encode all fields values

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/field_codec.dart
- packages/widgetbook/test/src/routing/non_ascii_chars_test.dart
When url with non-ascii symbols opened it gave error for twice parsed url.
For example (sandbox app):
If i will open URL
http://localhost:{port}/#/?path=settings/nullablesetting/default&knobs={Description:%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82} or http://localhost:{port}/#/?path=settings/nullablesetting/default&knobs={%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82:asciiword} (first option non-ascii used as value, in second option as key)
in browser i will get this error on screenshot.
This happens for severl reasons:
In router information already exist Uri decoded query parameters.
For string_field.dart method Uri.decodeComponent called twice. …
> fix: skip decoding non-ascii characters

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/widgetbook.dart
Today, widgetbook uses [constant predefined theme](https://github.com/widgetbook/widgetbook/blob/f65e24018ca3f2afdeda2aae19744f7fd32c001d/packages/widgetbook/lib/src/widgetbook.dart#L113-L114) which means one can't personalize widgetbook.
This PR aims to allow customisation of Widgetbook's theme.
Closes #1183 
> feat: allow custom theming

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/api/api.dart
- packages/widgetbook_cli/lib/src/api/models/build_draft_request.dart
- packages/widgetbook_cli/lib/src/api/models/build_draft_response.dart
- packages/widgetbook_cli/lib/src/api/storage_client.dart
- packages/widgetbook_cli/lib/src/api/widgetbook_http_client.dart
- packages/widgetbook_cli/lib/src/commands/build_push.dart
- packages/widgetbook_cli/lib/src/storage/storage.dart
- packages/widgetbook_cli/lib/src/storage/storage_client.dart
- packages/widgetbook_cli/lib/src/storage/storage_object.dart
- packages/widgetbook_cli/pubspec.yaml
Directly upload build files to storage, bypassing Widgetbook Cloud's server. This enhancement ensures that builds are instantly available on Widgetbook Cloud upon completion of the `cloud build push` command, eliminating the need for additional processing.
> refactor(cli): upload files directly to storage

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/api/models/build_draft_request.dart
- packages/widgetbook_cli/lib/src/api/models/build_draft_response.dart
- packages/widgetbook_cli/lib/src/commands/build_push.dart
- packages/widgetbook_cli/lib/src/storage/storage_client.dart
- packages/widgetbook_cli/lib/src/storage/storage_object.dart
- packages/widgetbook_cli/pubspec.yaml
The `build push` command used to send a map of all the files paths and their sizes to the server, then receive a map with files paths and their urls. 
This approach was memory/time consuming on our server when the build had a lot of files. The server will now only send 1 URL back, that can be re-used among all files.
> refactor(cli): reduce build draft payload size

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/lib/src/knobs/builders/knobs_builder.dart
- packages/widgetbook/test/src/knobs/list_knob_test.dart
Remove the default value, _which was the first item in `options`_, for the `listOrNull` knob.
> fix: remove default value for `listOrNull` knob

- packages/widgetbook_cli/lib/src/commands/build_push.dart
- packages/widgetbook_cli/lib/src/storage/storage_client.dart
- packages/widgetbook_cli/lib/src/storage/storage_object.dart
Reading all the `StorageObject` at once was causing issues due to a lot of concurrent open files. The implementation is adjusted to delay reading the steam only when needed in the `_uploadObject(...)` function.
> fix(cli): open streams on upload

- analysis_options.yaml
- examples/full_example/analysis_options.yaml
- examples/knobs_example/analysis_options.yaml
- examples/monorepo_example/apps/admin_app/analysis_options.yaml
- examples/monorepo_example/apps/main_app/analysis_options.yaml
- examples/monorepo_example/packages/shared_ui/analysis_options.yaml
- examples/monorepo_example/widgetbook/analysis_options.yaml
- examples/screen_util_example/analysis_options.yaml
- packages/widgetbook/analysis_options.yaml
- packages/widgetbook/test/src/fields/duration_field_test.dart
- packages/widgetbook_annotation/analysis_options.yaml
- packages/widgetbook_cli/analysis_options.yaml
- packages/widgetbook_cli/lib/src/commands/cloud.dart
- packages/widgetbook_cli/lib/src/commands/upgrade.dart
- packages/widgetbook_generator/analysis_options.yaml
- packages/widgetbook_generator/test/helpers/code.dart
- packages/widgetbook_test/analysis_options.yaml
- pubspec.lock
- pubspec.yaml
- sandbox/analysis_options.yaml
Our old setup had only 1 `analysis_options.yaml` in the root of the repo, this file imported `very_good_analysis` package. Such setup wasn't working properly in all sub-folders, and a lot of rules were skipped.
We now have root `analysis_options.yaml` file in the root, but also an `analysis_options.yaml` file in each package/app that includes this root file.
The `very_good_analysis` packages was removed because it gives a warning in the sub-file.
> chore: add `analysis_options.yaml` to all packages

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
The dependency was added #842 to enforce minimum `widgetbook` version with `widgetbook_generator`. This is no longer needed for new versions.
Such dependency affects our `widgetbook_generator` score, because it depends on a package that uses Flutter, while the generator itself doesn't use Flutter.
> deps(generator): remove `widgetbook` dependency

- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook.yaml
- examples/full_example/pubspec.lock
- examples/knobs_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/screen_util_example/pubspec.lock
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
- packages/widgetbook/lib/src/themes.dart
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- pubspec.yaml
- sandbox/pubspec.lock
The minimum versions for Dart and Flutter are now 3.0.0 and 3.16.0 respectively.
Reasons for such change:
1. Allow `accessibility_tools` v1.0.1 that requires Flutter 3.16, to get our package score back, and have a green CI again that was failing due to the `pana` job. **[failed]**
2. Use new language features from Dart 3.
3. Reduce deprecated code that was ignored due to supporting Flutter 3.7, which was released more than a year ago.
> deps: bump sdk to 3 & flutter to 3.16

- docs/addons/text-scale-addon.mdx
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
- packages/widgetbook/lib/src/next/addons/text_scale_addon.dart
- packages/widgetbook/test/src/addons/text_scale_factor_test.dart
`MediaQuery.textScaleFactor` was deprecated in Flutter 3.16.0.
Since we have bumped our minimum Flutter version to 3.16.0, we can now use `TextScaler`.
More info: https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor
> refactor: use `textScaler` in `TextScaleAddon`

- packages/widgetbook/lib/src/routing/app_route_parser.dart
- packages/widgetbook/lib/src/routing/app_router.dart
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/test/src/routing/app_router_delegate_test.dart
A lot of code was there to get around the deprecation of `location` in Flutter 3.13.
This code now can be safely remove after we have bumped the minimum Flutter version 3.16.
> refactor: remove router deprecated code

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/commands/build_push.dart
Fixes the RegEx pattern not matching the `<base href>` tag for older Flutter version as those end on ` />` instead of the expected `>`
> fix: `base href` replacement

- docs/guides/assets.mdx
In the docs, fix for the `pubspec.yaml` example file for the assets folder
The `sdk` version line needs to be indented under `environment`. When copying and pasting the code as it is, the `pubspec.yaml` file is not valid.
- N/A I added new tests to check the change I am making.
> docs: fix indentation in assets guide

- examples/full_example/pubspec.lock
- examples/knobs_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/screen_util_example/pubspec.lock
- packages/widgetbook/pubspec.yaml
- sandbox/pubspec.lock
Since our minimum flutter version is now 3.16 (#1243), we can now use `accessibility_tools` 2.x.x
> deps: bump `accessibility_tools` to v2

- examples/full_example/pubspec.lock
- examples/knobs_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/screen_util_example/pubspec.lock
- sandbox/pubspec.lock
Update our examples to use Flutter 3.24.1, no package updates included.
> chore: upgrade to flutter 3.24.1

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/commands/build_push.dart
- packages/widgetbook_cli/lib/src/core/context.dart
- packages/widgetbook_cli/lib/src/core/context_manager.dart
- packages/widgetbook_cli/lib/src/git/reference.dart
- packages/widgetbook_cli/test/src/core/context_manager_test.dart
The following CLI arguments will now have defaults from Azure Pipelines:
| Argument | Default |
| :----- | :----- |
| `--branch` | `Build.SourceBranch` or `System.PullRequest.SourceBranch` |
| `--repository` | `Build.Repository.Name` |
| `--actor` | `Build.SourceVersionAuthor` |
> fix(cli): update azure context defaults

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/core/context_manager.dart
- packages/widgetbook_cli/test/src/core/context_manager_test.dart
The following CLI arguments will now have defaults from GitLab Pipelines:
| Argument | Default |
| :----- | :----- |
| `--commit` | `CI_COMMIT_SHA` | 
| `--branch` | `CI_COMMIT_BRANCH` |
| `--repository` | `CI_PROJECT_PATH` |
| `--actor` | `GITLAB_USER_LOGIN` |
> fix(cli): update gitlab context defaults

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/list_field.dart
- packages/widgetbook/test/src/knobs/list_knob_test.dart
`DropdownMenu` now takes the width of its parent.
> refactor: expand `DropdownMenu` width

- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/storage/storage_object.dart
When the files are uploaded to storage from a windows, they are created as root files instead of files within folders. This is because our storage only supports POSIX paths.
> fix(cli): convert windows paths to posix

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/navigation/widgets/navigation_panel.dart
- packages/widgetbook/test/src/navigation/widgets/navigation_panel_test.dart
Escapes all special characters received as a part of search string which are treated differently in RegExp. 
- [1276](https://github.com/widgetbook/widgetbook/issues/1276)
> fix: allow special characters in search query

- docs/cloud/index.mdx
We had an incorrect get access link that did not lead to the product.
> docs: fix cloud access link

- docs/guides/quick-start.mdx
Fix a typo in the docs from `pubsepc.yaml` to `pubspec.yaml`
- Typo
> docs: fix typo

- docs/addons/index.mdx
Was copying some code from the docs and noticed a deprecation.
> docs: update `TextScaleAddon` deprecated usage

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/state/widgetbook_scope.dart
- packages/widgetbook/lib/widgetbook.dart
- packages/widgetbook/test/helper/tester_extension.dart
Expose the internal `WidgetbookScope` class as some users are using it for testing. The class was imported in `test/` directory as follows:
```dart
import 'package:widgetbook/src/state/widgetbook_scope.dart';
```
After this PR, the following import should be possible
```dart
import 'package:widgetbook/widgetbook.dart';
```
> fix: expose `WidgetbookScope`

- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
In the generator, we used the `pubspec.lock` to resolve some paths in case of local packages. This logic will now be partially skipped if the lock file was not found.
The path resolution logic may be removed in the future, since we do not really use it.
> fix(generator): escape path resolution for missing resource

- examples/knobs_example/lib/widgetbook.dart
- packages/widgetbook/lib/src/addons/grid_addon/grid_addon.dart
- packages/widgetbook/lib/src/fields/color_field/color_field.dart
- packages/widgetbook/lib/src/fields/color_field/color_picker.dart
- packages/widgetbook/lib/src/fields/color_field/opaque_color.dart
- packages/widgetbook/lib/src/navigation/widgets/search_field.dart
- packages/widgetbook/lib/src/next/addons/grid_addon.dart
- packages/widgetbook/lib/src/next/args/story_args.dart
- packages/widgetbook/lib/src/themes.dart
- There was a lot of `Color`-related deprecation, because of [wide gamut Color](https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework).
- `whereNotNull` was deprecated in `package:collection`, in favor of Dart's `nonNulls`.
> fix: resolve flutter 3.27 deprecations

- .github/workflows/widgetbook-annotation.yaml
- .github/workflows/widgetbook-cli.yaml
- .github/workflows/widgetbook-generator.yaml
- .github/workflows/widgetbook-test.yaml
- .github/workflows/widgetbook.yaml
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/color_field/color_field.dart
- packages/widgetbook/lib/src/fields/color_field/color_picker.dart
- packages/widgetbook/lib/src/fields/color_field/opaque_color.dart
- packages/widgetbook/lib/src/routing/app_router_delegate.dart
- packages/widgetbook/lib/src/themes.dart
- packages/widgetbook/pubspec.yaml
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/pubspec.yaml
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_test/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Starting from today, we keep our minimum SDK/Flutter versions to the fourth latest one.
As of today, the four latest Flutter releases are:
1. Flutter v3.27 + Dart v3.6
2. Flutter v3.24 + Dart v3.5
3. Flutter v3.22 + Dart v3.4
4. Flutter v3.19 + Dart v3.3 (our minimum versions)
> deps: bump sdk to 3.3 & flutter to 3.19

- packages/widgetbook_cli/pubspec.yaml
Update dependencies to match our new SDK constraint 3.3 from #1349
> chore(cli): update deps

- examples/screen_util_example/lib/widgetbook.dart
- examples/screen_util_example/pubspec.lock
- examples/screen_util_example/pubspec.yaml
`flutter_screenutil` >= 5.9.2 stopped using `MediaQuery.of` and started using `View.of` in OpenFlutter/flutter_screenutil@f7c551acd4cc82460c3a29ec5a7262d6ec678746.
This causes widgets to get misplaced/misaligned as we [wrap](https://github.com/widgetbook/widgetbook/blob/9b0542dc14879d3db28ce3e87fc81e919608c40b/packages/widgetbook/lib/src/workbench/safe_boundaries.dart#L19-L27) our workbench in a `MediaQuery` widget.
> fix(example): pin `flutter_screenutil` version

- packages/widgetbook_cli/pubspec.yaml
The packages `mason_logger` and `pub_updater` had a `^0.x.y` constraint which did not allow new versions (0.x+1.0), thus the constraint is widened to allow those releases, and earn the lost pub points.
> chore(cli): relax 0.x packages constraint

- packages/widgetbook/lib/src/addons/semantics_addon/semantics_addon.dart
The field name in `SemanticsAddon` and `SemanticsAddonConfig` was mismatching.
> fix: match semantics addon and config fields

- examples/full_example/pubspec.lock
- examples/knobs_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/screen_util_example/pubspec.lock
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_setting.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/none_device.dart
- packages/widgetbook/lib/src/next/addons/device_frame_addon.dart
- packages/widgetbook/pubspec.yaml
- sandbox/pubspec.lock
Since `device_frame` is no longer maintained. We will be using `device_frame_plus` before we deprecate the addon in the upcoming releases.
> refactor: use `device_frame_plus`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/layout/responsive_layout.dart
- packages/widgetbook/test/src/layout/responsive_layout_test.dart
The desktop layout does not really work on a tablet in portrait orientation. The navigation has many overflows and is generally too small to actually read any use case names, etc. The same applies to the knobs and addons UI on the right.
According to https://m3.material.io/foundations/layout/applying-layout/window-size-classes#2bb70e22-d09b-4b73-9c9f-9ef60311ccc8 the limit for desktop, landscape tablet, etc. is 840, not 800. With 840, our tablets also now correctly switch between desktop for landscape and mobile for portrait.
https://github.com/widgetbook/widgetbook/issues/1415
> refactor: adjust mobile breakpoint

- docs/guides/customization.mdx
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/state/default_home_builder.dart
- packages/widgetbook/lib/src/state/default_home_page.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/src/widgetbook.dart
- packages/widgetbook/lib/src/workbench/workbench.dart
- packages/widgetbook/test/src/workbench/workbench_test.dart
The home widget is a widget that is shown on startup when no use-case is selected. This widget does not inherit from the `appBuilder` or the `addons`; Meaning that if `Theme.of(context)` is called inside this widget, then it will use Widgetbook's `lightTheme` or `darkTheme`, and not the Theme from the `appBuilder` or the `ThemeAddon`.
> feat: add `home` widget

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/workbench/workbench.dart
Using an old context to retrieve the `WidgetbookState` resulted in outdated states in some cases. When an old state is used, the [key](https://github.com/widgetbook/widgetbook/blob/5f07675bd26d094f09091694c588889e1b972a24/packages/widgetbook/lib/src/workbench/workbench.dart#L52) used in `UseCaseBuilder` remained the same, which prevented the `initState` from being re-called, resulting in knobs not being [`lock()`ed](https://github.com/widgetbook/widgetbook/blob/5f07675bd26d094f09091694c588889e1b972a24/packages/widgetbook/lib/src/workbench/use_case_builder.dart#L26).
> fix: ensure fresh state

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/themes.dart
> fix: unify `color` knob fields' heights

- docs/guides/embedding.mdx
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/layout/desktop_layout.dart
- packages/widgetbook/lib/src/routing/app_route_config.dart
- packages/widgetbook/lib/src/settings/settings_panel.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/lib/src/utils.dart
- packages/widgetbook/test/src/layout/desktop_layout_test.dart
- packages/widgetbook/test/src/settings/settings_panel_test.dart
The `panels` query parameter allows to customize the embedded Widgetbook view by hiding or showing certain panels. For example `?panels=addons,knobs` hides the left navigation panel.
> feat: add `panels` query parameter

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/date_time_field.dart
The `TextFormField` value did not reflect the `DateTimeField` value when the picker was used, because Flutter did not rebuild the widget (since is it a stateless one). So by using a `key`, we are forcing Flutter to rebuild the field, when we know it has a different value.
> fix: rebuild `DateTimeField` after using the picker

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/lib/src/fields/fields_composable.dart
- packages/widgetbook/lib/src/knobs/knob.dart
- packages/widgetbook/lib/src/knobs/knobs_registry.dart
- packages/widgetbook/lib/src/next/args/arg.dart
- packages/widgetbook/lib/src/settings/nullable_setting.dart
- packages/widgetbook/test/src/fields/fields_composable_test.dart
- packages/widgetbook/test/src/knobs/knob_test.dart
- packages/widgetbook/test/src/knobs/string_knob_test.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
- sandbox/lib/settings/nullable_setting.dart
Previously, the null state of the knob was held inside the `Knob` class, and not reflected in the URL. This prevented the `nullable` knobs from being supported in the `KnobConfig` for multi-snapshot feature.
With this PR, nullable knobs can be expressed as follows:
1. `/?path=my-use-case&knobs={my-knob:??}` - just null
2. `/?path=my-use-case&knobs={my-knob:??my-value}` - `my-value` will be used when the knob is activated via the checkbox.
> refactor: rework nullable knobs

- docs/cloud/reviews/multi-snapshot.mdx
- docs/knobs/bool.mdx
- docs/knobs/color.mdx
- docs/knobs/datetime.mdx
- docs/knobs/double/overview.mdx
- docs/knobs/duration.mdx
- docs/knobs/integer/overview.mdx
- docs/knobs/list.mdx
- docs/knobs/string.mdx
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/knob_config.dart
- sandbox/lib/settings/nullable_setting.dart
If a knob can be `null` (i.e. using the `orNull` variant), then now it can have a `KnobConfig` using the new `NullKnobConfig`:
```dart
@UseCase(
name: 'Default',
type: MyWidget,
cloudKnobsConfigs: {
'Without text': [NullKnobConfig('text')],
'With text': [StringKnobConfig('text', 'lorem ipusm')],
},
)
Widget buildUseCase(BuildContext context) {
return MyWidget(
text: context.knobs.stringOrNull(label: 'text'),
);
}
```
> feat(annotation): add `NullKnobConfig`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/viewport_addon/viewport.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewport_data.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/android_viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/ios_viewports.dart
Add padding info to `MediaQuery`, to make `SafeArea` widget behave correctly inside the `ViewportAddon`.
| Before | After |
| ------ | ----- |
| ![before](https://github.com/user-attachments/assets/8f1eb5f7-7eab-4797-837b-887bb8cb85f7) | ![after](https://github.com/user-attachments/assets/c6ca347d-d2d4-4593-afe7-238ac3ff3ffb) |
> feat: add `safeAreas` to viewports

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/viewport_addon/viewport.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewport_addon.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewport_data.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/android_viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/ios_viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/linux_viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/macos_viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/viewports.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/windows_viewports.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/addons_configs_builder.dart
Since it's not possible to customize the dropdown menu to show viewports names, while still using IDs under the hood, we are removing the `id` as a whole, and replacing it with the `name`.
> refactor: remove viewport `id`

- examples/feature_preview/lib/knob-preview.dart
The typedef caused the structure to differ from what is expected in the docs. 
`widgets/Widget/*` 
`KnobPreview/*`
> fix(preview): restructure nav paths

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/themes.dart
Flutter 3.32 introduced a breaking change of changing the type of `tabBarTheme` from `TabBarTheme` to `TabBarThemeData`. Since we support older version of Flutter, we cannot just do that change. Instead, the same color was applied via `ColorScheme.outlineVariant`.
> fix: support flutter 3.32

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/pubspec.yaml
Tightens dependency constraint for `device_frame_plus` to avoid a breaking change introduced in v1.4.0.
Hotfix for #1474 
> fix: tighten `device_frame_plus` constraint

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
Fixes https://github.com/widgetbook/widgetbook/issues/1486
> fix: dispose `KnobsRegistry` from `WidgetbookState`

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/color_field/hex_color_picker.dart
- packages/widgetbook/lib/src/fields/color_field/number_text_field.dart
- packages/widgetbook/lib/src/fields/date_time_field.dart
- packages/widgetbook/lib/src/fields/duration_field.dart
- packages/widgetbook/lib/src/fields/num_input_field.dart
- packages/widgetbook/lib/src/fields/string_field.dart
- packages/widgetbook/test/src/fields/color_field_test.dart
- packages/widgetbook/test/src/fields/date_time_field_test.dart
- packages/widgetbook/test/src/fields/duration_field_test.dart
- packages/widgetbook/test/src/fields/num_input_field_test.dart
- packages/widgetbook/test/src/fields/string_field_test.dart
I'm getting errors from the Widgetbook and not from my components with AccessibilityTools
```sh
Accessibility issue 1: Text field is missing a label.
Consider adding a hint or a label to the text field widget. For example:
TextField(
inputDecoration: InputDecoration(hint: 'This is hint'),
)
```
> fix: add hint text to input fields

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/viewport_addon/viewport.dart
Some users might override the root `Theme` in their `appBuilder` as follows:
```dart
Widgetbook.material(
appBuilder: (context, child) {
return MaterialApp(
theme: MyCustomThemeData()
); 
}
)
```
If `MyCustomThemeData` doesn't have a proper `TextTheme`, then the `Viewport`'s title will get messed up.
This PR uses the `WidgetbookTheme` to ensure that it matches Widgetbook's own theme, and not any other theme down the widget tree.
> fix: preserve viewport's title style

- docs/addons/device-frame-addon.mdx
- examples/full_example/lib/widgetbook.dart
- examples/screen_util_example/lib/widgetbook.dart
- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/common/widgetbook_addon.dart
- packages/widgetbook/lib/src/addons/device_frame_addon/device_frame_addon.dart
- packages/widgetbook/test/src/addons/device_frame_addon_test.dart
The `DeviceFrameAddon` is deprecated because we aim to keep our next major version without much dependencies. That's why we introduced a first-class support for the same feature via the [`ViewportAddon`](https://docs.widgetbook.io/addons/viewport-addon).
> refactor: deprecate `DeviceFrameAddon`

- docs/cloud/snapshots/overview.mdx
- packages/widgetbook_annotation/CHANGELOG.md
- packages/widgetbook_annotation/lib/src/use_case.dart
- packages/widgetbook_cli/CHANGELOG.md
- packages/widgetbook_cli/lib/src/cache/cache_reader.dart
- packages/widgetbook_cli/lib/src/cache/use_case_metadata.dart
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
- packages/widgetbook_generator/lib/src/models/use_case_metadata.dart
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_generator/test/helpers/mock_use_case_metadata.dart
- sandbox/lib/navigation/navigation_panel.dart
Some Widgetbook Cloud users like to exclude some use-cases from being processed.
This new option allows them to achieve that.
```dart
@UseCase(
name: 'Default',
type: UnstableWidget,
cloudExclude: true
)
Widget buildUseCase(BuildContext context) { ... }
```
> feat: allow excluding use-cases from cloud

- examples/feature_preview/pubspec.lock
- examples/feature_preview/pubspec.yaml
- examples/full_example/pubspec.lock
- examples/full_example/pubspec.yaml
- examples/monorepo_example/widgetbook/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.yaml
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/app_generator.dart
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
- packages/widgetbook_generator/lib/src/next/arg_builder.dart
- packages/widgetbook_generator/lib/src/next/args_class_builder.dart
- packages/widgetbook_generator/lib/src/next/component_builder.dart
- packages/widgetbook_generator/lib/src/next/components_builder.dart
- packages/widgetbook_generator/lib/src/next/extensions.dart
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- packages/widgetbook_generator/lib/src/next/story_generator.dart
- packages/widgetbook_generator/pubspec.yaml
- packages/widgetbook_generator/test/helpers/code.dart
- sandbox/pubspec.lock
- sandbox/pubspec.yaml
The [new Elements API](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/element_model_migration_guide.md) will become the new default in `analyzer` v8.
> refactor(generator): migrate to new elements api

- packages/widgetbook_cli/lib/src/core/cli_command.dart
The error handling in `CliCommand` is not needed. The `CliRunner` has a top-level [error handler](https://github.com/widgetbook/widgetbook/blob/6e3145c8df2026f69f9f59e082c8fbff0ab9381a/packages/widgetbook_cli/lib/src/core/cli_runner.dart#L61-L69).
> refactor(cli): remove command error handling

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/device_frame_addon/none_device.dart
- packages/widgetbook/lib/src/addons/semantics_addon/minimal_semantics_debugger.dart
- packages/widgetbook/lib/src/addons/viewport_addon/viewports/viewports.dart
- packages/widgetbook/lib/src/knobs/knobs_registry.dart
Ignore warnings from Flutter 3.35.0 as they are needed for our minimum supported Flutter version (3.29.0).
The ignored warning can be resolved once Flutter 3.35.0 becomes our minimum version.
> fix: support flutter 3.35

- examples/feature_preview/pubspec.lock
- examples/full_example/pubspec.lock
- examples/monorepo_example/widgetbook/pubspec.lock
- packages/widgetbook_generator/CHANGELOG.md
- packages/widgetbook_generator/lib/src/generators/app_generator.dart
- packages/widgetbook_generator/lib/src/generators/use_case_generator.dart
- packages/widgetbook_generator/lib/src/next/arg_builder.dart
- packages/widgetbook_generator/lib/src/next/args_class_builder.dart
- packages/widgetbook_generator/lib/src/next/component_builder.dart
- packages/widgetbook_generator/lib/src/next/components_builder.dart
- packages/widgetbook_generator/lib/src/next/extensions.dart
- packages/widgetbook_generator/lib/src/next/story_class_builder.dart
- packages/widgetbook_generator/lib/src/next/story_generator.dart
- packages/widgetbook_generator/pubspec.yaml
- sandbox/pubspec.lock
Support `analyzer` v8.
Currently we still support `analyzer` v7 as well, so we have to use the `element2` APIs, and ignore the deprecations until we drop analyzer 7 support.
> refactor(generator): allow analyzer 8.x

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/field.dart
- packages/widgetbook/test/src/fields/field_test.dart
By default, changing the value of a disabled knob enable it. When we manually enable and then disable a knob, changing the value didn't enable the knob.
- https://github.com/widgetbook/widgetbook/issues/1585
https://github.com/user-attachments/assets/3a63441f-2cdf-44c4-9467-f7392f54de07
> fix: re-enable nullified fields on change

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/fields/num_slider_field.dart
- packages/widgetbook/test/src/fields/num_slider_field_test.dart
To avoid NumSliderField to throw when the value exceed higher or lower limit, we can use clamp() to restrict the value.
- https://github.com/widgetbook/widgetbook/issues/1589
https://github.com/user-attachments/assets/ef3b83e5-1209-4cd7-9233-23e4301cca82
> fix: clamp num slider field value

- packages/widgetbook/CHANGELOG.md
- packages/widgetbook/lib/src/addons/semantics_addon/minimal_semantics_debugger.dart
As a QA i would check quickly semantics in web. Actually semantics are not displayed using full screen on my MacOs as the devicePixelRatio is 2. As 1 / 2 equal 0.5, is scale by 0.5...
https://github.com/widgetbook/widgetbook/issues/1612
> fix: scale semantics addon properly

- examples/full_example/lib/customs/custom_arg.dart
- packages/widgetbook/lib/src/args/bool_arg.dart
- packages/widgetbook/lib/src/args/color_arg.dart
- packages/widgetbook/lib/src/args/double_arg.dart
- packages/widgetbook/lib/src/args/duration_arg.dart
- packages/widgetbook/lib/src/args/int_arg.dart
- packages/widgetbook/lib/src/args/single_arg.dart
- packages/widgetbook/lib/src/args/string_arg.dart
- packages/widgetbook/lib/src/core/arg.dart
- packages/widgetbook/lib/src/core/const_arg.dart
- packages/widgetbook/lib/src/state/widgetbook_state.dart
- packages/widgetbook/test/src/state/widgetbook_state_test.dart
- sandbox/lib/[sam]/types_table.stories.dart
This makes it cleaner for multi-field args, for example a `PersonArg`:
- Before `args={person.name:foo,person.age:25,other:x}`
- After `person={name:foo,age:25}&other={value:x}` _(note: `other` will be shortened to `other=x` later)_
> refactor: expand args query group
